import {
  APP_NAME,
  LABS_NAME,
  PAGE_DESC_SITEMAP,
  SEO_ALIASES,
  SEO_CANONICAL,
  SEO_DESCRIPTION,
  SEO_TAB_AGENT,
  SEO_TAB_BEARS,
  SEO_TAB_OWL,
  SEO_TAB_CALLING_BOTS,
  SEO_TAB_COFFEE,
  SEO_TAB_COMPUTE,
  SEO_TAB_DESK,
  SEO_TAB_FEED,
  SEO_TAB_GM,
  SEO_TAB_LAB,
  TAB_AGENT,
  TAB_BEARS,
  TAB_OWL,
  TAB_CALLING_BOTS,
  TAB_COFFEE,
  TAB_COMPUTE,
  TAB_DESK,
  TAB_FEED,
  TAB_GM,
  TAB_HELLO,
  TAB_LAB,
} from "@/lib/brand";
import { COMPANY_X_URL } from "@/lib/desk/x-admin";

export function SeoCopy() {
  const data = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        name: LABS_NAME,
        alternateName: [APP_NAME, "S1R1US Labs", "S1R1US Bot Hedge Fund", TAB_DESK, SEO_TAB_DESK],
        url: SEO_CANONICAL,
        description: SEO_DESCRIPTION,
        sameAs: [COMPANY_X_URL, "https://github.com/S1R1US-AI/S1R1US-LABs"].filter(Boolean),
      },
      {
        "@type": "WebSite",
        name: LABS_NAME,
        alternateName: [APP_NAME, "AI Bitcoin trading bot", "AI Hedge Fund", TAB_DESK, TAB_GM, TAB_LAB, TAB_HELLO],
        url: SEO_CANONICAL,
        description: SEO_DESCRIPTION,
        potentialAction: {
          "@type": "SearchAction",
          target: `${SEO_CANONICAL}?q={search_term_string}`,
          "query-input": "required name=search_term_string",
        },
      },
      {
        "@type": "SoftwareApplication",
        name: TAB_DESK,
        alternateName: [SEO_TAB_DESK, APP_NAME, LABS_NAME, "S1R1US Bot Hedge Fund", "AI Bitcoin trading bot", "AI stock trading bot", "AI Hedge Fund"],
        applicationCategory: "FinanceApplication",
        operatingSystem: "Web",
        description: SEO_DESCRIPTION,
        url: SEO_CANONICAL,
      },
      {
        "@type": "SoftwareApplication",
        name: TAB_GM,
        alternateName: [SEO_TAB_GM, "Godzilla Mode", "Godzilla mode"],
        applicationCategory: "FinanceApplication",
        operatingSystem: "Web",
        description: `${TAB_GM} is Godzilla mode, the aggressive AI bitcoin sleeve of S1R1US Labs.`,
        url: `${SEO_CANONICAL}gm`,
      },
      {
        "@type": "Article",
        name: TAB_BEARS,
        headline: "How to beat the Bears at market speed with AI Agents",
        alternateName: [SEO_TAB_BEARS, "How to beat the Bears at market speed with AI Agents"],
        description: `${TAB_BEARS} is ${SEO_TAB_BEARS}. Theoretical loop for an AI agent reading Bot 7 to accumulate bitcoin on its own Coinbase. ${TAB_GM} (${SEO_TAB_GM}).`,
        url: `${SEO_CANONICAL}b3ars`,
        image: `${SEO_CANONICAL}gzilla-mrkt.png`,
      },
      {
        "@type": "Article",
        name: TAB_OWL,
        headline: "Wise investment decisions, theoretically optimized by AI agents",
        alternateName: [SEO_TAB_OWL, "Wise Owl", "AI trading bots", "Bitcoin trading agents", "wise investment"],
        description: `${TAB_OWL} is ${SEO_TAB_OWL}. AI trading bots and Bitcoin trading agents. Bot 7 tape plus Grok, Claude, and GPT analysis combined for a current bitcoin accumulation read.`,
        url: `${SEO_CANONICAL}owl`,
        image: `${SEO_CANONICAL}owl.png`,
      },
      {
        "@type": "WebPage",
        name: TAB_FEED,
        alternateName: [SEO_TAB_FEED, "Feed Hosting", "F33D G0dZiLLa M0D3", "F33D N0W"],
        description: `${TAB_FEED} is ${SEO_TAB_FEED}. Optional donations for hosting, domain, and open-source apps.`,
        url: `${SEO_CANONICAL}f33d`,
      },
      {
        "@type": "WebPage",
        name: TAB_HELLO,
        alternateName: ["Hello World", "H3LL0 W0RLD"],
        description: `${TAB_HELLO} is Hello World. Expand greeting on the public tape. Links to OP3N S0URC3 (open source). MaX1UM G@1Ns (Maximum Gains) opens Godzilla mode. S3Nd 2 BTC Wall3t (Send to BTC Wallet) opens F33D H0ST1Ng (Feed Hosting). Call1ng All B0Ts (Calling All Bots) opens the Agent feed.`,
        url: SEO_CANONICAL,
      },
      {
        "@type": "SoftwareApplication",
        name: TAB_LAB,
        alternateName: [SEO_TAB_LAB, "S1R1US Lab Strategies"],
        applicationCategory: "FinanceApplication",
        operatingSystem: "Web",
        description: `${TAB_LAB} is S1R1US Lab Strategies, the what-if overlay on the 7-bot tape.`,
        url: `${SEO_CANONICAL}helios`,
      },
      {
        "@type": "SoftwareSourceCode",
        name: "OP3N S0URC3",
        alternateName: ["open source", "H3LP 7-B0T H3DGE FUND [ S1R1U$ <<L@B$>> ] G0 >> OP3N S0URC3", "HELP 7-BOT HEDGE FUND GO OPEN SOURCE"],
        codeRepository: "https://github.com/S1R1US-AI/S1R1US-LABs",
        description: "OP3N S0URC3 is open source. GitHub repository started 2026-09-04: S1R1US-AI/S1R1US-LABs.",
        url: "https://github.com/S1R1US-AI/S1R1US-LABs",
      },
      {
        "@type": "FAQPage",
        name: `FAQ · ${TAB_DESK} · ${TAB_GM} · ${TAB_FEED} · ${TAB_LAB} · ${TAB_COFFEE} · ${TAB_CALLING_BOTS}`,
        url: `${SEO_CANONICAL}faq`,
        description: "FAQ for S1R1US 7-bot hedge fund, Godzilla mode, S1R1US Lab Strategies, Token launch, Buy Me a Cup of Coffee, Calling All Bots, open source. Not financial advice. Not an offer of securities.",
      },
      {
        "@type": "WebPage",
        name: "Terms and Agreements",
        url: `${SEO_CANONICAL}terms`,
        description: "Using this website constitutes agreement. Not financial advice. Seek a licensed professional. Not an offer of securities.",
      },
      {
        "@type": "WebPage",
        name: "Sitemap",
        url: `${SEO_CANONICAL}sitemap`,
        description: PAGE_DESC_SITEMAP,
      },
      {
        "@type": "WebPage",
        name: TAB_COFFEE,
        alternateName: [SEO_TAB_COFFEE, "C0FF33", "cup of coffee"],
        url: `${SEO_CANONICAL}c0ff33`,
        description: `${TAB_COFFEE} is ${SEO_TAB_COFFEE}. Optional $4.20 gift in BTC or native USDC to assist long programming days at s1r1us.ai. Unconditional gift. No tokens.`,
      },
      {
        "@type": "DonateAction",
        name: TAB_COFFEE,
        alternateName: SEO_TAB_COFFEE,
        description: "Optional $4.20 cup of coffee. Same BTC and USDC receive addresses as F33D H0ST1Ng (Feed Hosting).",
        target: `${SEO_CANONICAL}c0ff33`,
        recipient: { "@type": "Organization", name: LABS_NAME, url: SEO_CANONICAL },
      },
      {
        "@type": "WebPage",
        name: TAB_AGENT,
        alternateName: [SEO_TAB_AGENT, TAB_CALLING_BOTS, SEO_TAB_CALLING_BOTS, "Bot 7", "AI trading bots", "Bitcoin trading agents"],
        url: `${SEO_CANONICAL}agent`,
        description: `${TAB_CALLING_BOTS} (${SEO_TAB_CALLING_BOTS}). ${TAB_AGENT} (${SEO_TAB_AGENT}) is the read-only Bot 7 JSON and MCP for Grok, Claude, and GPT. AI trading bots. Bitcoin trading agents.`,
      },
      {
        "@type": "WebAPI",
        name: `${TAB_AGENT} (${SEO_TAB_AGENT})`,
        description: "START HERE for Grok, Claude, GPT, Coinbase for Agents. Read-only Bot 7 call. This host never trades.",
        documentation: `${SEO_CANONICAL}agent`,
        url: `${SEO_CANONICAL}api/agent/call`,
        provider: { "@type": "Organization", name: LABS_NAME, url: SEO_CANONICAL },
        termsOfService: `${SEO_CANONICAL}terms`,
      },
      {
        "@type": "EntryPoint",
        name: "llms.txt for AI agents",
        url: `${SEO_CANONICAL}llms.txt`,
        description: "Instruction file for Grok, Claude, GPT, and other AI agents. Come here first.",
      },
      {
        "@type": "WebPage",
        name: "Privacy Policy",
        url: `${SEO_CANONICAL}privacy`,
        description: "No bot may retain system information. No reverse engineering without S1R1US.ai authorization.",
      },
      {
        "@type": "WebPage",
        name: TAB_COMPUTE,
        alternateName: [SEO_TAB_COMPUTE, "Ask Grok", "BYO compute"],
        url: `${SEO_CANONICAL}compute`,
        description: `${TAB_COMPUTE} is ${SEO_TAB_COMPUTE}. Sign in with X, paste your xAI API key, Ask Grok on your bill. This host never stores the key.`,
      },
    ],
  };
  return (
    <>
      <p className="seo-copy sr-only" aria-hidden="true">{SEO_ALIASES}</p>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, "\\u003c") }} />
    </>
  );
}
