/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AiCatalogDotjsonRouteImport } from './routes/ai-catalog[.]json'
import { Route as AppRouteImport } from './routes/app'
import { Route as B3arsRouteImport } from './routes/b3ars'
import { Route as BoardRouteImport } from './routes/board'
import { Route as BowlRouteImport } from './routes/bowl'
import { Route as C0ff33RouteImport } from './routes/c0ff33'
import { Route as C0utRouteImport } from './routes/c0ut'
import { Route as CoffeeRouteImport } from './routes/coffee'
import { Route as ComputeRouteImport } from './routes/compute'
import { Route as CupRouteImport } from './routes/cup'
import { Route as EntityDotjsonRouteImport } from './routes/entity[.]json'
import { Route as F33dRouteImport } from './routes/f33d'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as GmRouteImport } from './routes/gm'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as H1v3RouteImport } from './routes/h1v3'
import { Route as HeliosRouteImport } from './routes/helios'
import { Route as HeliosbotRouteImport } from './routes/heliosbot'
import { Route as HiveRouteImport } from './routes/hive'
import { Route as IosRouteImport } from './routes/ios'
import { Route as L0ckRouteImport } from './routes/l0ck'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LockRouteImport } from './routes/lock'
import { Route as Lock3dRouteImport } from './routes/lock3d'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as MediaRouteImport } from './routes/media'
import { Route as OssRoadmapRouteImport } from './routes/oss-roadmap'
import { Route as OwlRouteImport } from './routes/owl'
import { Route as PlayRouteImport } from './routes/play'
import { Route as Pr3dRouteImport } from './routes/pr3d'
import { Route as PredRouteImport } from './routes/pred'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as R0b0tsRouteImport } from './routes/r0b0ts'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as S1r1usRouteImport } from './routes/s1r1us'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SimRouteImport } from './routes/sim'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourceRouteImport } from './routes/source'
import { Route as SwarmRouteImport } from './routes/swarm'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as VideoSitemapDotxmlRouteImport } from './routes/video-sitemap[.]xml'
import { Route as W0rldRouteImport } from './routes/w0rld'
import { Route as Wh1t3RouteImport } from './routes/wh1t3'
import { Route as WorldCupRouteImport } from './routes/world-cup'
import { Route as DotwellKnownAgentCardDotjsonRouteImport } from './routes/[.]well-known/agent-card[.]json'
import { Route as DotwellKnownAgentDotjsonRouteImport } from './routes/[.]well-known/agent[.]json'
import { Route as DotwellKnownAiCatalogDotjsonRouteImport } from './routes/[.]well-known/ai-catalog[.]json'
import { Route as DotwellKnownAiPluginDotjsonRouteImport } from './routes/[.]well-known/ai-plugin[.]json'
import { Route as DotwellKnownAppleAppSiteAssociationRouteImport } from './routes/[.]well-known/apple-app-site-association'
import { Route as DotwellKnownAssetlinksDotjsonRouteImport } from './routes/[.]well-known/assetlinks[.]json'
import { Route as DotwellKnownLlmsDottxtRouteImport } from './routes/[.]well-known/llms[.]txt'
import { Route as DotwellKnownMcpServerDotjsonRouteImport } from './routes/[.]well-known/mcp-server[.]json'
import { Route as DotwellKnownMcpDotjsonRouteImport } from './routes/[.]well-known/mcp[.]json'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as AppAdminRouteImport } from './routes/app_.admin'
import { Route as BoardIdRouteImport } from './routes/board.$id'
import { Route as MorningPdfIdRouteImport } from './routes/morning-pdf.$id'
import { Route as DotwellKnownMcpServerCardDotjsonRouteImport } from './routes/[.]well-known/mcp/server-card[.]json'
import { Route as ApiAgentA2aRouteImport } from './routes/api/agent.a2a'
import { Route as ApiAgentAppRouteImport } from './routes/api/agent.app'
import { Route as ApiAgentAppleRouteImport } from './routes/api/agent.apple'
import { Route as ApiAgentBoardRouteImport } from './routes/api/agent.board'
import { Route as ApiAgentCallRouteImport } from './routes/api/agent/call'
import { Route as ApiAgentCardRouteImport } from './routes/api/agent.card'
import { Route as ApiAgentClaudeRouteImport } from './routes/api/agent.claude'
import { Route as ApiAgentConnectRouteImport } from './routes/api/agent.connect'
import { Route as ApiAgentCupRouteImport } from './routes/api/agent.cup'
import { Route as ApiAgentFeeRouteImport } from './routes/api/agent.fee'
import { Route as ApiAgentForumRouteImport } from './routes/api/agent.forum'
import { Route as ApiAgentGoogleRouteImport } from './routes/api/agent.google'
import { Route as ApiAgentGrokRouteImport } from './routes/api/agent.grok'
import { Route as ApiAgentHiveRouteImport } from './routes/api/agent.hive'
import { Route as ApiAgentKeysRouteImport } from './routes/api/agent.keys'
import { Route as ApiAgentLocksRouteImport } from './routes/api/agent.locks'
import { Route as ApiAgentMcpRouteImport } from './routes/api/agent.mcp'
import { Route as ApiAgentNoticesRouteImport } from './routes/api/agent.notices'
import { Route as ApiAgentOpenaiRouteImport } from './routes/api/agent.openai'
import { Route as ApiAgentOpenapiRouteImport } from './routes/api/agent.openapi'
import { Route as ApiAgentPingRouteImport } from './routes/api/agent.ping'
import { Route as ApiAgentPredRouteImport } from './routes/api/agent.pred'
import { Route as ApiAgentRoadmapRouteImport } from './routes/api/agent.roadmap'
import { Route as ApiAgentSiriRouteImport } from './routes/api/agent.siri'
import { Route as ApiAgentWaitlistRouteImport } from './routes/api/agent.waitlist'
import { Route as ApiAgentWebmcpRouteImport } from './routes/api/agent.webmcp'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentBoardPicIdRouteImport } from './routes/api/agent.board.pic.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCatalogDotjsonRoute = AiCatalogDotjsonRouteImport.update({
  id: '/ai-catalog.json',
  path: '/ai-catalog.json',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const B3arsRoute = B3arsRouteImport.update({
  id: '/b3ars',
  path: '/b3ars',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const BowlRoute = BowlRouteImport.update({
  id: '/bowl',
  path: '/bowl',
  getParentRoute: () => rootRouteImport,
} as any)
const C0ff33Route = C0ff33RouteImport.update({
  id: '/c0ff33',
  path: '/c0ff33',
  getParentRoute: () => rootRouteImport,
} as any)
const C0utRoute = C0utRouteImport.update({
  id: '/c0ut',
  path: '/c0ut',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeRoute = CoffeeRouteImport.update({
  id: '/coffee',
  path: '/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeRoute = ComputeRouteImport.update({
  id: '/compute',
  path: '/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const CupRoute = CupRouteImport.update({
  id: '/cup',
  path: '/cup',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityDotjsonRoute = EntityDotjsonRouteImport.update({
  id: '/entity.json',
  path: '/entity.json',
  getParentRoute: () => rootRouteImport,
} as any)
const F33dRoute = F33dRouteImport.update({
  id: '/f33d',
  path: '/f33d',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const GmRoute = GmRouteImport.update({
  id: '/gm',
  path: '/gm',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const H1v3Route = H1v3RouteImport.update({
  id: '/h1v3',
  path: '/h1v3',
  getParentRoute: () => rootRouteImport,
} as any)
const HeliosRoute = HeliosRouteImport.update({
  id: '/helios',
  path: '/helios',
  getParentRoute: () => rootRouteImport,
} as any)
const HeliosbotRoute = HeliosbotRouteImport.update({
  id: '/heliosbot',
  path: '/heliosbot',
  getParentRoute: () => rootRouteImport,
} as any)
const HiveRoute = HiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => rootRouteImport,
} as any)
const IosRoute = IosRouteImport.update({
  id: '/ios',
  path: '/ios',
  getParentRoute: () => rootRouteImport,
} as any)
const L0ckRoute = L0ckRouteImport.update({
  id: '/l0ck',
  path: '/l0ck',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const Lock3dRoute = Lock3dRouteImport.update({
  id: '/lock3d',
  path: '/lock3d',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const OssRoadmapRoute = OssRoadmapRouteImport.update({
  id: '/oss-roadmap',
  path: '/oss-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const OwlRoute = OwlRouteImport.update({
  id: '/owl',
  path: '/owl',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const Pr3dRoute = Pr3dRouteImport.update({
  id: '/pr3d',
  path: '/pr3d',
  getParentRoute: () => rootRouteImport,
} as any)
const PredRoute = PredRouteImport.update({
  id: '/pred',
  path: '/pred',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const R0b0tsRoute = R0b0tsRouteImport.update({
  id: '/r0b0ts',
  path: '/r0b0ts',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const S1r1usRoute = S1r1usRouteImport.update({
  id: '/s1r1us',
  path: '/s1r1us',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SimRoute = SimRouteImport.update({
  id: '/sim',
  path: '/sim',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const SwarmRoute = SwarmRouteImport.update({
  id: '/swarm',
  path: '/swarm',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoSitemapDotxmlRoute = VideoSitemapDotxmlRouteImport.update({
  id: '/video-sitemap.xml',
  path: '/video-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const W0rldRoute = W0rldRouteImport.update({
  id: '/w0rld',
  path: '/w0rld',
  getParentRoute: () => rootRouteImport,
} as any)
const Wh1t3Route = Wh1t3RouteImport.update({
  id: '/wh1t3',
  path: '/wh1t3',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldCupRoute = WorldCupRouteImport.update({
  id: '/world-cup',
  path: '/world-cup',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentCardDotjsonRoute =
  DotwellKnownAgentCardDotjsonRouteImport.update({
    id: '/.well-known/agent-card.json',
    path: '/.well-known/agent-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentDotjsonRoute =
  DotwellKnownAgentDotjsonRouteImport.update({
    id: '/.well-known/agent.json',
    path: '/.well-known/agent.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAiCatalogDotjsonRoute =
  DotwellKnownAiCatalogDotjsonRouteImport.update({
    id: '/.well-known/ai-catalog.json',
    path: '/.well-known/ai-catalog.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAiPluginDotjsonRoute =
  DotwellKnownAiPluginDotjsonRouteImport.update({
    id: '/.well-known/ai-plugin.json',
    path: '/.well-known/ai-plugin.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAppleAppSiteAssociationRoute =
  DotwellKnownAppleAppSiteAssociationRouteImport.update({
    id: '/.well-known/apple-app-site-association',
    path: '/.well-known/apple-app-site-association',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAssetlinksDotjsonRoute =
  DotwellKnownAssetlinksDotjsonRouteImport.update({
    id: '/.well-known/assetlinks.json',
    path: '/.well-known/assetlinks.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownLlmsDottxtRoute = DotwellKnownLlmsDottxtRouteImport.update({
  id: '/.well-known/llms.txt',
  path: '/.well-known/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpServerDotjsonRoute =
  DotwellKnownMcpServerDotjsonRouteImport.update({
    id: '/.well-known/mcp-server.json',
    path: '/.well-known/mcp-server.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownMcpDotjsonRoute = DotwellKnownMcpDotjsonRouteImport.update({
  id: '/.well-known/mcp.json',
  path: '/.well-known/mcp.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/app_/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardIdRoute = BoardIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BoardRoute,
} as any)
const MorningPdfIdRoute = MorningPdfIdRouteImport.update({
  id: '/morning-pdf/$id',
  path: '/morning-pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownMcpServerCardDotjsonRoute =
  DotwellKnownMcpServerCardDotjsonRouteImport.update({
    id: '/.well-known/mcp/server-card.json',
    path: '/.well-known/mcp/server-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentA2aRoute = ApiAgentA2aRouteImport.update({
  id: '/a2a',
  path: '/a2a',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentAppRoute = ApiAgentAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentAppleRoute = ApiAgentAppleRouteImport.update({
  id: '/apple',
  path: '/apple',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentBoardRoute = ApiAgentBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentCallRoute = ApiAgentCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentCardRoute = ApiAgentCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentClaudeRoute = ApiAgentClaudeRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentConnectRoute = ApiAgentConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentCupRoute = ApiAgentCupRouteImport.update({
  id: '/cup',
  path: '/cup',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentFeeRoute = ApiAgentFeeRouteImport.update({
  id: '/fee',
  path: '/fee',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentForumRoute = ApiAgentForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentGoogleRoute = ApiAgentGoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentGrokRoute = ApiAgentGrokRouteImport.update({
  id: '/grok',
  path: '/grok',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentHiveRoute = ApiAgentHiveRouteImport.update({
  id: '/hive',
  path: '/hive',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentKeysRoute = ApiAgentKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentLocksRoute = ApiAgentLocksRouteImport.update({
  id: '/locks',
  path: '/locks',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentMcpRoute = ApiAgentMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentNoticesRoute = ApiAgentNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentOpenaiRoute = ApiAgentOpenaiRouteImport.update({
  id: '/openai',
  path: '/openai',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentOpenapiRoute = ApiAgentOpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentPingRoute = ApiAgentPingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentPredRoute = ApiAgentPredRouteImport.update({
  id: '/pred',
  path: '/pred',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentRoadmapRoute = ApiAgentRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentSiriRoute = ApiAgentSiriRouteImport.update({
  id: '/siri',
  path: '/siri',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentWaitlistRoute = ApiAgentWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentWebmcpRoute = ApiAgentWebmcpRouteImport.update({
  id: '/webmcp',
  path: '/webmcp',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentBoardPicIdRoute = ApiAgentBoardPicIdRouteImport.update({
  id: '/pic/$id',
  path: '/pic/$id',
  getParentRoute: () => ApiAgentBoardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/ai-catalog.json': typeof AiCatalogDotjsonRoute
  '/app': typeof AppRoute
  '/b3ars': typeof B3arsRoute
  '/board': typeof BoardRouteWithChildren
  '/bowl': typeof BowlRoute
  '/c0ff33': typeof C0ff33Route
  '/c0ut': typeof C0utRoute
  '/coffee': typeof CoffeeRoute
  '/compute': typeof ComputeRoute
  '/cup': typeof CupRoute
  '/entity.json': typeof EntityDotjsonRoute
  '/f33d': typeof F33dRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/gm': typeof GmRoute
  '/guide': typeof GuideRoute
  '/h1v3': typeof H1v3Route
  '/helios': typeof HeliosRoute
  '/heliosbot': typeof HeliosbotRoute
  '/hive': typeof HiveRoute
  '/ios': typeof IosRoute
  '/l0ck': typeof L0ckRoute
  '/launch': typeof LaunchRoute
  '/lock': typeof LockRoute
  '/lock3d': typeof Lock3dRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/media': typeof MediaRoute
  '/oss-roadmap': typeof OssRoadmapRoute
  '/owl': typeof OwlRoute
  '/play': typeof PlayRoute
  '/pr3d': typeof Pr3dRoute
  '/pred': typeof PredRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/r0b0ts': typeof R0b0tsRoute
  '/renew': typeof RenewRoute
  '/roadmap': typeof RoadmapRoute
  '/s1r1us': typeof S1r1usRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/sim': typeof SimRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/swarm': typeof SwarmRoute
  '/terms': typeof TermsRoute
  '/theme': typeof ThemeRoute
  '/video-sitemap.xml': typeof VideoSitemapDotxmlRoute
  '/w0rld': typeof W0rldRoute
  '/wh1t3': typeof Wh1t3Route
  '/world-cup': typeof WorldCupRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/ai-plugin.json': typeof DotwellKnownAiPluginDotjsonRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/.well-known/llms.txt': typeof DotwellKnownLlmsDottxtRoute
  '/.well-known/mcp-server.json': typeof DotwellKnownMcpServerDotjsonRoute
  '/.well-known/mcp.json': typeof DotwellKnownMcpDotjsonRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/board/$id': typeof BoardIdRoute
  '/morning-pdf/$id': typeof MorningPdfIdRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/agent/a2a': typeof ApiAgentA2aRoute
  '/api/agent/app': typeof ApiAgentAppRoute
  '/api/agent/apple': typeof ApiAgentAppleRoute
  '/api/agent/board': typeof ApiAgentBoardRouteWithChildren
  '/api/agent/call': typeof ApiAgentCallRoute
  '/api/agent/card': typeof ApiAgentCardRoute
  '/api/agent/claude': typeof ApiAgentClaudeRoute
  '/api/agent/connect': typeof ApiAgentConnectRoute
  '/api/agent/cup': typeof ApiAgentCupRoute
  '/api/agent/fee': typeof ApiAgentFeeRoute
  '/api/agent/forum': typeof ApiAgentForumRoute
  '/api/agent/google': typeof ApiAgentGoogleRoute
  '/api/agent/grok': typeof ApiAgentGrokRoute
  '/api/agent/hive': typeof ApiAgentHiveRoute
  '/api/agent/keys': typeof ApiAgentKeysRoute
  '/api/agent/locks': typeof ApiAgentLocksRoute
  '/api/agent/mcp': typeof ApiAgentMcpRoute
  '/api/agent/notices': typeof ApiAgentNoticesRoute
  '/api/agent/openai': typeof ApiAgentOpenaiRoute
  '/api/agent/openapi': typeof ApiAgentOpenapiRoute
  '/api/agent/ping': typeof ApiAgentPingRoute
  '/api/agent/pred': typeof ApiAgentPredRoute
  '/api/agent/roadmap': typeof ApiAgentRoadmapRoute
  '/api/agent/siri': typeof ApiAgentSiriRoute
  '/api/agent/waitlist': typeof ApiAgentWaitlistRoute
  '/api/agent/webmcp': typeof ApiAgentWebmcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/agent/board/pic/$id': typeof ApiAgentBoardPicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/ai-catalog.json': typeof AiCatalogDotjsonRoute
  '/app': typeof AppRoute
  '/b3ars': typeof B3arsRoute
  '/board': typeof BoardRouteWithChildren
  '/bowl': typeof BowlRoute
  '/c0ff33': typeof C0ff33Route
  '/c0ut': typeof C0utRoute
  '/coffee': typeof CoffeeRoute
  '/compute': typeof ComputeRoute
  '/cup': typeof CupRoute
  '/entity.json': typeof EntityDotjsonRoute
  '/f33d': typeof F33dRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/gm': typeof GmRoute
  '/guide': typeof GuideRoute
  '/h1v3': typeof H1v3Route
  '/helios': typeof HeliosRoute
  '/heliosbot': typeof HeliosbotRoute
  '/hive': typeof HiveRoute
  '/ios': typeof IosRoute
  '/l0ck': typeof L0ckRoute
  '/launch': typeof LaunchRoute
  '/lock': typeof LockRoute
  '/lock3d': typeof Lock3dRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/media': typeof MediaRoute
  '/oss-roadmap': typeof OssRoadmapRoute
  '/owl': typeof OwlRoute
  '/play': typeof PlayRoute
  '/pr3d': typeof Pr3dRoute
  '/pred': typeof PredRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/r0b0ts': typeof R0b0tsRoute
  '/renew': typeof RenewRoute
  '/roadmap': typeof RoadmapRoute
  '/s1r1us': typeof S1r1usRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/sim': typeof SimRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/swarm': typeof SwarmRoute
  '/terms': typeof TermsRoute
  '/theme': typeof ThemeRoute
  '/video-sitemap.xml': typeof VideoSitemapDotxmlRoute
  '/w0rld': typeof W0rldRoute
  '/wh1t3': typeof Wh1t3Route
  '/world-cup': typeof WorldCupRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/ai-plugin.json': typeof DotwellKnownAiPluginDotjsonRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/.well-known/llms.txt': typeof DotwellKnownLlmsDottxtRoute
  '/.well-known/mcp-server.json': typeof DotwellKnownMcpServerDotjsonRoute
  '/.well-known/mcp.json': typeof DotwellKnownMcpDotjsonRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/board/$id': typeof BoardIdRoute
  '/morning-pdf/$id': typeof MorningPdfIdRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/agent/a2a': typeof ApiAgentA2aRoute
  '/api/agent/app': typeof ApiAgentAppRoute
  '/api/agent/apple': typeof ApiAgentAppleRoute
  '/api/agent/board': typeof ApiAgentBoardRouteWithChildren
  '/api/agent/call': typeof ApiAgentCallRoute
  '/api/agent/card': typeof ApiAgentCardRoute
  '/api/agent/claude': typeof ApiAgentClaudeRoute
  '/api/agent/connect': typeof ApiAgentConnectRoute
  '/api/agent/cup': typeof ApiAgentCupRoute
  '/api/agent/fee': typeof ApiAgentFeeRoute
  '/api/agent/forum': typeof ApiAgentForumRoute
  '/api/agent/google': typeof ApiAgentGoogleRoute
  '/api/agent/grok': typeof ApiAgentGrokRoute
  '/api/agent/hive': typeof ApiAgentHiveRoute
  '/api/agent/keys': typeof ApiAgentKeysRoute
  '/api/agent/locks': typeof ApiAgentLocksRoute
  '/api/agent/mcp': typeof ApiAgentMcpRoute
  '/api/agent/notices': typeof ApiAgentNoticesRoute
  '/api/agent/openai': typeof ApiAgentOpenaiRoute
  '/api/agent/openapi': typeof ApiAgentOpenapiRoute
  '/api/agent/ping': typeof ApiAgentPingRoute
  '/api/agent/pred': typeof ApiAgentPredRoute
  '/api/agent/roadmap': typeof ApiAgentRoadmapRoute
  '/api/agent/siri': typeof ApiAgentSiriRoute
  '/api/agent/waitlist': typeof ApiAgentWaitlistRoute
  '/api/agent/webmcp': typeof ApiAgentWebmcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/agent/board/pic/$id': typeof ApiAgentBoardPicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/ai-catalog.json': typeof AiCatalogDotjsonRoute
  '/app': typeof AppRoute
  '/b3ars': typeof B3arsRoute
  '/board': typeof BoardRouteWithChildren
  '/bowl': typeof BowlRoute
  '/c0ff33': typeof C0ff33Route
  '/c0ut': typeof C0utRoute
  '/coffee': typeof CoffeeRoute
  '/compute': typeof ComputeRoute
  '/cup': typeof CupRoute
  '/entity.json': typeof EntityDotjsonRoute
  '/f33d': typeof F33dRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/gm': typeof GmRoute
  '/guide': typeof GuideRoute
  '/h1v3': typeof H1v3Route
  '/helios': typeof HeliosRoute
  '/heliosbot': typeof HeliosbotRoute
  '/hive': typeof HiveRoute
  '/ios': typeof IosRoute
  '/l0ck': typeof L0ckRoute
  '/launch': typeof LaunchRoute
  '/lock': typeof LockRoute
  '/lock3d': typeof Lock3dRoute
  '/login': typeof LoginRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/media': typeof MediaRoute
  '/oss-roadmap': typeof OssRoadmapRoute
  '/owl': typeof OwlRoute
  '/play': typeof PlayRoute
  '/pr3d': typeof Pr3dRoute
  '/pred': typeof PredRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/r0b0ts': typeof R0b0tsRoute
  '/renew': typeof RenewRoute
  '/roadmap': typeof RoadmapRoute
  '/s1r1us': typeof S1r1usRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/sim': typeof SimRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/swarm': typeof SwarmRoute
  '/terms': typeof TermsRoute
  '/theme': typeof ThemeRoute
  '/video-sitemap.xml': typeof VideoSitemapDotxmlRoute
  '/w0rld': typeof W0rldRoute
  '/wh1t3': typeof Wh1t3Route
  '/world-cup': typeof WorldCupRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/ai-catalog.json': typeof DotwellKnownAiCatalogDotjsonRoute
  '/.well-known/ai-plugin.json': typeof DotwellKnownAiPluginDotjsonRoute
  '/.well-known/apple-app-site-association': typeof DotwellKnownAppleAppSiteAssociationRoute
  '/.well-known/assetlinks.json': typeof DotwellKnownAssetlinksDotjsonRoute
  '/.well-known/llms.txt': typeof DotwellKnownLlmsDottxtRoute
  '/.well-known/mcp-server.json': typeof DotwellKnownMcpServerDotjsonRoute
  '/.well-known/mcp.json': typeof DotwellKnownMcpDotjsonRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/app_/admin': typeof AppAdminRoute
  '/board/$id': typeof BoardIdRoute
  '/morning-pdf/$id': typeof MorningPdfIdRoute
  '/.well-known/mcp/server-card.json': typeof DotwellKnownMcpServerCardDotjsonRoute
  '/api/agent/a2a': typeof ApiAgentA2aRoute
  '/api/agent/app': typeof ApiAgentAppRoute
  '/api/agent/apple': typeof ApiAgentAppleRoute
  '/api/agent/board': typeof ApiAgentBoardRouteWithChildren
  '/api/agent/call': typeof ApiAgentCallRoute
  '/api/agent/card': typeof ApiAgentCardRoute
  '/api/agent/claude': typeof ApiAgentClaudeRoute
  '/api/agent/connect': typeof ApiAgentConnectRoute
  '/api/agent/cup': typeof ApiAgentCupRoute
  '/api/agent/fee': typeof ApiAgentFeeRoute
  '/api/agent/forum': typeof ApiAgentForumRoute
  '/api/agent/google': typeof ApiAgentGoogleRoute
  '/api/agent/grok': typeof ApiAgentGrokRoute
  '/api/agent/hive': typeof ApiAgentHiveRoute
  '/api/agent/keys': typeof ApiAgentKeysRoute
  '/api/agent/locks': typeof ApiAgentLocksRoute
  '/api/agent/mcp': typeof ApiAgentMcpRoute
  '/api/agent/notices': typeof ApiAgentNoticesRoute
  '/api/agent/openai': typeof ApiAgentOpenaiRoute
  '/api/agent/openapi': typeof ApiAgentOpenapiRoute
  '/api/agent/ping': typeof ApiAgentPingRoute
  '/api/agent/pred': typeof ApiAgentPredRoute
  '/api/agent/roadmap': typeof ApiAgentRoadmapRoute
  '/api/agent/siri': typeof ApiAgentSiriRoute
  '/api/agent/waitlist': typeof ApiAgentWaitlistRoute
  '/api/agent/webmcp': typeof ApiAgentWebmcpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/agent/board/pic/$id': typeof ApiAgentBoardPicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/ai-catalog.json'
    | '/app'
    | '/b3ars'
    | '/board'
    | '/bowl'
    | '/c0ff33'
    | '/c0ut'
    | '/coffee'
    | '/compute'
    | '/cup'
    | '/entity.json'
    | '/f33d'
    | '/faq'
    | '/forum'
    | '/gm'
    | '/guide'
    | '/h1v3'
    | '/helios'
    | '/heliosbot'
    | '/hive'
    | '/ios'
    | '/l0ck'
    | '/launch'
    | '/lock'
    | '/lock3d'
    | '/login'
    | '/manifest.webmanifest'
    | '/media'
    | '/oss-roadmap'
    | '/owl'
    | '/play'
    | '/pr3d'
    | '/pred'
    | '/predictions'
    | '/privacy'
    | '/r0b0ts'
    | '/renew'
    | '/roadmap'
    | '/s1r1us'
    | '/search'
    | '/security'
    | '/sim'
    | '/sitemap'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/source'
    | '/swarm'
    | '/terms'
    | '/theme'
    | '/video-sitemap.xml'
    | '/w0rld'
    | '/wh1t3'
    | '/world-cup'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/ai-plugin.json'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/.well-known/llms.txt'
    | '/.well-known/mcp-server.json'
    | '/.well-known/mcp.json'
    | '/api/agent'
    | '/app/admin'
    | '/board/$id'
    | '/morning-pdf/$id'
    | '/.well-known/mcp/server-card.json'
    | '/api/agent/a2a'
    | '/api/agent/app'
    | '/api/agent/apple'
    | '/api/agent/board'
    | '/api/agent/call'
    | '/api/agent/card'
    | '/api/agent/claude'
    | '/api/agent/connect'
    | '/api/agent/cup'
    | '/api/agent/fee'
    | '/api/agent/forum'
    | '/api/agent/google'
    | '/api/agent/grok'
    | '/api/agent/hive'
    | '/api/agent/keys'
    | '/api/agent/locks'
    | '/api/agent/mcp'
    | '/api/agent/notices'
    | '/api/agent/openai'
    | '/api/agent/openapi'
    | '/api/agent/ping'
    | '/api/agent/pred'
    | '/api/agent/roadmap'
    | '/api/agent/siri'
    | '/api/agent/waitlist'
    | '/api/agent/webmcp'
    | '/api/auth/$'
    | '/api/agent/board/pic/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/ai-catalog.json'
    | '/app'
    | '/b3ars'
    | '/board'
    | '/bowl'
    | '/c0ff33'
    | '/c0ut'
    | '/coffee'
    | '/compute'
    | '/cup'
    | '/entity.json'
    | '/f33d'
    | '/faq'
    | '/forum'
    | '/gm'
    | '/guide'
    | '/h1v3'
    | '/helios'
    | '/heliosbot'
    | '/hive'
    | '/ios'
    | '/l0ck'
    | '/launch'
    | '/lock'
    | '/lock3d'
    | '/login'
    | '/manifest.webmanifest'
    | '/media'
    | '/oss-roadmap'
    | '/owl'
    | '/play'
    | '/pr3d'
    | '/pred'
    | '/predictions'
    | '/privacy'
    | '/r0b0ts'
    | '/renew'
    | '/roadmap'
    | '/s1r1us'
    | '/search'
    | '/security'
    | '/sim'
    | '/sitemap'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/source'
    | '/swarm'
    | '/terms'
    | '/theme'
    | '/video-sitemap.xml'
    | '/w0rld'
    | '/wh1t3'
    | '/world-cup'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/ai-plugin.json'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/.well-known/llms.txt'
    | '/.well-known/mcp-server.json'
    | '/.well-known/mcp.json'
    | '/api/agent'
    | '/app/admin'
    | '/board/$id'
    | '/morning-pdf/$id'
    | '/.well-known/mcp/server-card.json'
    | '/api/agent/a2a'
    | '/api/agent/app'
    | '/api/agent/apple'
    | '/api/agent/board'
    | '/api/agent/call'
    | '/api/agent/card'
    | '/api/agent/claude'
    | '/api/agent/connect'
    | '/api/agent/cup'
    | '/api/agent/fee'
    | '/api/agent/forum'
    | '/api/agent/google'
    | '/api/agent/grok'
    | '/api/agent/hive'
    | '/api/agent/keys'
    | '/api/agent/locks'
    | '/api/agent/mcp'
    | '/api/agent/notices'
    | '/api/agent/openai'
    | '/api/agent/openapi'
    | '/api/agent/ping'
    | '/api/agent/pred'
    | '/api/agent/roadmap'
    | '/api/agent/siri'
    | '/api/agent/waitlist'
    | '/api/agent/webmcp'
    | '/api/auth/$'
    | '/api/agent/board/pic/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/ai-catalog.json'
    | '/app'
    | '/b3ars'
    | '/board'
    | '/bowl'
    | '/c0ff33'
    | '/c0ut'
    | '/coffee'
    | '/compute'
    | '/cup'
    | '/entity.json'
    | '/f33d'
    | '/faq'
    | '/forum'
    | '/gm'
    | '/guide'
    | '/h1v3'
    | '/helios'
    | '/heliosbot'
    | '/hive'
    | '/ios'
    | '/l0ck'
    | '/launch'
    | '/lock'
    | '/lock3d'
    | '/login'
    | '/manifest.webmanifest'
    | '/media'
    | '/oss-roadmap'
    | '/owl'
    | '/play'
    | '/pr3d'
    | '/pred'
    | '/predictions'
    | '/privacy'
    | '/r0b0ts'
    | '/renew'
    | '/roadmap'
    | '/s1r1us'
    | '/search'
    | '/security'
    | '/sim'
    | '/sitemap'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/source'
    | '/swarm'
    | '/terms'
    | '/theme'
    | '/video-sitemap.xml'
    | '/w0rld'
    | '/wh1t3'
    | '/world-cup'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/ai-catalog.json'
    | '/.well-known/ai-plugin.json'
    | '/.well-known/apple-app-site-association'
    | '/.well-known/assetlinks.json'
    | '/.well-known/llms.txt'
    | '/.well-known/mcp-server.json'
    | '/.well-known/mcp.json'
    | '/api/agent'
    | '/app_/admin'
    | '/board/$id'
    | '/morning-pdf/$id'
    | '/.well-known/mcp/server-card.json'
    | '/api/agent/a2a'
    | '/api/agent/app'
    | '/api/agent/apple'
    | '/api/agent/board'
    | '/api/agent/call'
    | '/api/agent/card'
    | '/api/agent/claude'
    | '/api/agent/connect'
    | '/api/agent/cup'
    | '/api/agent/fee'
    | '/api/agent/forum'
    | '/api/agent/google'
    | '/api/agent/grok'
    | '/api/agent/hive'
    | '/api/agent/keys'
    | '/api/agent/locks'
    | '/api/agent/mcp'
    | '/api/agent/notices'
    | '/api/agent/openai'
    | '/api/agent/openapi'
    | '/api/agent/ping'
    | '/api/agent/pred'
    | '/api/agent/roadmap'
    | '/api/agent/siri'
    | '/api/agent/waitlist'
    | '/api/agent/webmcp'
    | '/api/auth/$'
    | '/api/agent/board/pic/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  AiCatalogDotjsonRoute: typeof AiCatalogDotjsonRoute
  AppRoute: typeof AppRoute
  B3arsRoute: typeof B3arsRoute
  BoardRoute: typeof BoardRouteWithChildren
  BowlRoute: typeof BowlRoute
  C0ff33Route: typeof C0ff33Route
  C0utRoute: typeof C0utRoute
  CoffeeRoute: typeof CoffeeRoute
  ComputeRoute: typeof ComputeRoute
  CupRoute: typeof CupRoute
  EntityDotjsonRoute: typeof EntityDotjsonRoute
  F33dRoute: typeof F33dRoute
  FaqRoute: typeof FaqRoute
  ForumRoute: typeof ForumRoute
  GmRoute: typeof GmRoute
  GuideRoute: typeof GuideRoute
  H1v3Route: typeof H1v3Route
  HeliosRoute: typeof HeliosRoute
  HeliosbotRoute: typeof HeliosbotRoute
  HiveRoute: typeof HiveRoute
  IosRoute: typeof IosRoute
  L0ckRoute: typeof L0ckRoute
  LaunchRoute: typeof LaunchRoute
  LockRoute: typeof LockRoute
  Lock3dRoute: typeof Lock3dRoute
  LoginRoute: typeof LoginRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  MediaRoute: typeof MediaRoute
  OssRoadmapRoute: typeof OssRoadmapRoute
  OwlRoute: typeof OwlRoute
  PlayRoute: typeof PlayRoute
  Pr3dRoute: typeof Pr3dRoute
  PredRoute: typeof PredRoute
  PredictionsRoute: typeof PredictionsRoute
  PrivacyRoute: typeof PrivacyRoute
  R0b0tsRoute: typeof R0b0tsRoute
  RenewRoute: typeof RenewRoute
  RoadmapRoute: typeof RoadmapRoute
  S1r1usRoute: typeof S1r1usRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  SimRoute: typeof SimRoute
  SitemapRoute: typeof SitemapRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourceRoute: typeof SourceRoute
  SwarmRoute: typeof SwarmRoute
  TermsRoute: typeof TermsRoute
  ThemeRoute: typeof ThemeRoute
  VideoSitemapDotxmlRoute: typeof VideoSitemapDotxmlRoute
  W0rldRoute: typeof W0rldRoute
  Wh1t3Route: typeof Wh1t3Route
  WorldCupRoute: typeof WorldCupRoute
  DotwellKnownAgentCardDotjsonRoute: typeof DotwellKnownAgentCardDotjsonRoute
  DotwellKnownAgentDotjsonRoute: typeof DotwellKnownAgentDotjsonRoute
  DotwellKnownAiCatalogDotjsonRoute: typeof DotwellKnownAiCatalogDotjsonRoute
  DotwellKnownAiPluginDotjsonRoute: typeof DotwellKnownAiPluginDotjsonRoute
  DotwellKnownAppleAppSiteAssociationRoute: typeof DotwellKnownAppleAppSiteAssociationRoute
  DotwellKnownAssetlinksDotjsonRoute: typeof DotwellKnownAssetlinksDotjsonRoute
  DotwellKnownLlmsDottxtRoute: typeof DotwellKnownLlmsDottxtRoute
  DotwellKnownMcpServerDotjsonRoute: typeof DotwellKnownMcpServerDotjsonRoute
  DotwellKnownMcpDotjsonRoute: typeof DotwellKnownMcpDotjsonRoute
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  AppAdminRoute: typeof AppAdminRoute
  MorningPdfIdRoute: typeof MorningPdfIdRoute
  DotwellKnownMcpServerCardDotjsonRoute: typeof DotwellKnownMcpServerCardDotjsonRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-catalog.json': {
      id: '/ai-catalog.json'
      path: '/ai-catalog.json'
      fullPath: '/ai-catalog.json'
      preLoaderRoute: typeof AiCatalogDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b3ars': {
      id: '/b3ars'
      path: '/b3ars'
      fullPath: '/b3ars'
      preLoaderRoute: typeof B3arsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bowl': {
      id: '/bowl'
      path: '/bowl'
      fullPath: '/bowl'
      preLoaderRoute: typeof BowlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c0ff33': {
      id: '/c0ff33'
      path: '/c0ff33'
      fullPath: '/c0ff33'
      preLoaderRoute: typeof C0ff33RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c0ut': {
      id: '/c0ut'
      path: '/c0ut'
      fullPath: '/c0ut'
      preLoaderRoute: typeof C0utRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee': {
      id: '/coffee'
      path: '/coffee'
      fullPath: '/coffee'
      preLoaderRoute: typeof CoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute': {
      id: '/compute'
      path: '/compute'
      fullPath: '/compute'
      preLoaderRoute: typeof ComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cup': {
      id: '/cup'
      path: '/cup'
      fullPath: '/cup'
      preLoaderRoute: typeof CupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity.json': {
      id: '/entity.json'
      path: '/entity.json'
      fullPath: '/entity.json'
      preLoaderRoute: typeof EntityDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f33d': {
      id: '/f33d'
      path: '/f33d'
      fullPath: '/f33d'
      preLoaderRoute: typeof F33dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm': {
      id: '/gm'
      path: '/gm'
      fullPath: '/gm'
      preLoaderRoute: typeof GmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h1v3': {
      id: '/h1v3'
      path: '/h1v3'
      fullPath: '/h1v3'
      preLoaderRoute: typeof H1v3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helios': {
      id: '/helios'
      path: '/helios'
      fullPath: '/helios'
      preLoaderRoute: typeof HeliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heliosbot': {
      id: '/heliosbot'
      path: '/heliosbot'
      fullPath: '/heliosbot'
      preLoaderRoute: typeof HeliosbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hive': {
      id: '/hive'
      path: '/hive'
      fullPath: '/hive'
      preLoaderRoute: typeof HiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ios': {
      id: '/ios'
      path: '/ios'
      fullPath: '/ios'
      preLoaderRoute: typeof IosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l0ck': {
      id: '/l0ck'
      path: '/l0ck'
      fullPath: '/l0ck'
      preLoaderRoute: typeof L0ckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock3d': {
      id: '/lock3d'
      path: '/lock3d'
      fullPath: '/lock3d'
      preLoaderRoute: typeof Lock3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oss-roadmap': {
      id: '/oss-roadmap'
      path: '/oss-roadmap'
      fullPath: '/oss-roadmap'
      preLoaderRoute: typeof OssRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owl': {
      id: '/owl'
      path: '/owl'
      fullPath: '/owl'
      preLoaderRoute: typeof OwlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pr3d': {
      id: '/pr3d'
      path: '/pr3d'
      fullPath: '/pr3d'
      preLoaderRoute: typeof Pr3dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pred': {
      id: '/pred'
      path: '/pred'
      fullPath: '/pred'
      preLoaderRoute: typeof PredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r0b0ts': {
      id: '/r0b0ts'
      path: '/r0b0ts'
      fullPath: '/r0b0ts'
      preLoaderRoute: typeof R0b0tsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s1r1us': {
      id: '/s1r1us'
      path: '/s1r1us'
      fullPath: '/s1r1us'
      preLoaderRoute: typeof S1r1usRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sim': {
      id: '/sim'
      path: '/sim'
      fullPath: '/sim'
      preLoaderRoute: typeof SimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swarm': {
      id: '/swarm'
      path: '/swarm'
      fullPath: '/swarm'
      preLoaderRoute: typeof SwarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-sitemap.xml': {
      id: '/video-sitemap.xml'
      path: '/video-sitemap.xml'
      fullPath: '/video-sitemap.xml'
      preLoaderRoute: typeof VideoSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w0rld': {
      id: '/w0rld'
      path: '/w0rld'
      fullPath: '/w0rld'
      preLoaderRoute: typeof W0rldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wh1t3': {
      id: '/wh1t3'
      path: '/wh1t3'
      fullPath: '/wh1t3'
      preLoaderRoute: typeof Wh1t3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world-cup': {
      id: '/world-cup'
      path: '/world-cup'
      fullPath: '/world-cup'
      preLoaderRoute: typeof WorldCupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-card.json': {
      id: '/.well-known/agent-card.json'
      path: '/.well-known/agent-card.json'
      fullPath: '/.well-known/agent-card.json'
      preLoaderRoute: typeof DotwellKnownAgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent.json': {
      id: '/.well-known/agent.json'
      path: '/.well-known/agent.json'
      fullPath: '/.well-known/agent.json'
      preLoaderRoute: typeof DotwellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/ai-catalog.json': {
      id: '/.well-known/ai-catalog.json'
      path: '/.well-known/ai-catalog.json'
      fullPath: '/.well-known/ai-catalog.json'
      preLoaderRoute: typeof DotwellKnownAiCatalogDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/ai-plugin.json': {
      id: '/.well-known/ai-plugin.json'
      path: '/.well-known/ai-plugin.json'
      fullPath: '/.well-known/ai-plugin.json'
      preLoaderRoute: typeof DotwellKnownAiPluginDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/apple-app-site-association': {
      id: '/.well-known/apple-app-site-association'
      path: '/.well-known/apple-app-site-association'
      fullPath: '/.well-known/apple-app-site-association'
      preLoaderRoute: typeof DotwellKnownAppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/assetlinks.json': {
      id: '/.well-known/assetlinks.json'
      path: '/.well-known/assetlinks.json'
      fullPath: '/.well-known/assetlinks.json'
      preLoaderRoute: typeof DotwellKnownAssetlinksDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/llms.txt': {
      id: '/.well-known/llms.txt'
      path: '/.well-known/llms.txt'
      fullPath: '/.well-known/llms.txt'
      preLoaderRoute: typeof DotwellKnownLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp-server.json': {
      id: '/.well-known/mcp-server.json'
      path: '/.well-known/mcp-server.json'
      fullPath: '/.well-known/mcp-server.json'
      preLoaderRoute: typeof DotwellKnownMcpServerDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp.json': {
      id: '/.well-known/mcp.json'
      path: '/.well-known/mcp.json'
      fullPath: '/.well-known/mcp.json'
      preLoaderRoute: typeof DotwellKnownMcpDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/admin': {
      id: '/app_/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board/$id': {
      id: '/board/$id'
      path: '/$id'
      fullPath: '/board/$id'
      preLoaderRoute: typeof BoardIdRouteImport
      parentRoute: typeof BoardRoute
    }
    '/morning-pdf/$id': {
      id: '/morning-pdf/$id'
      path: '/morning-pdf/$id'
      fullPath: '/morning-pdf/$id'
      preLoaderRoute: typeof MorningPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/mcp/server-card.json': {
      id: '/.well-known/mcp/server-card.json'
      path: '/.well-known/mcp/server-card.json'
      fullPath: '/.well-known/mcp/server-card.json'
      preLoaderRoute: typeof DotwellKnownMcpServerCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/a2a': {
      id: '/api/agent/a2a'
      path: '/a2a'
      fullPath: '/api/agent/a2a'
      preLoaderRoute: typeof ApiAgentA2aRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/app': {
      id: '/api/agent/app'
      path: '/app'
      fullPath: '/api/agent/app'
      preLoaderRoute: typeof ApiAgentAppRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/apple': {
      id: '/api/agent/apple'
      path: '/apple'
      fullPath: '/api/agent/apple'
      preLoaderRoute: typeof ApiAgentAppleRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/board': {
      id: '/api/agent/board'
      path: '/board'
      fullPath: '/api/agent/board'
      preLoaderRoute: typeof ApiAgentBoardRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/call': {
      id: '/api/agent/call'
      path: '/call'
      fullPath: '/api/agent/call'
      preLoaderRoute: typeof ApiAgentCallRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/card': {
      id: '/api/agent/card'
      path: '/card'
      fullPath: '/api/agent/card'
      preLoaderRoute: typeof ApiAgentCardRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/claude': {
      id: '/api/agent/claude'
      path: '/claude'
      fullPath: '/api/agent/claude'
      preLoaderRoute: typeof ApiAgentClaudeRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/connect': {
      id: '/api/agent/connect'
      path: '/connect'
      fullPath: '/api/agent/connect'
      preLoaderRoute: typeof ApiAgentConnectRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/cup': {
      id: '/api/agent/cup'
      path: '/cup'
      fullPath: '/api/agent/cup'
      preLoaderRoute: typeof ApiAgentCupRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/fee': {
      id: '/api/agent/fee'
      path: '/fee'
      fullPath: '/api/agent/fee'
      preLoaderRoute: typeof ApiAgentFeeRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/forum': {
      id: '/api/agent/forum'
      path: '/forum'
      fullPath: '/api/agent/forum'
      preLoaderRoute: typeof ApiAgentForumRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/google': {
      id: '/api/agent/google'
      path: '/google'
      fullPath: '/api/agent/google'
      preLoaderRoute: typeof ApiAgentGoogleRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/grok': {
      id: '/api/agent/grok'
      path: '/grok'
      fullPath: '/api/agent/grok'
      preLoaderRoute: typeof ApiAgentGrokRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/hive': {
      id: '/api/agent/hive'
      path: '/hive'
      fullPath: '/api/agent/hive'
      preLoaderRoute: typeof ApiAgentHiveRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/keys': {
      id: '/api/agent/keys'
      path: '/keys'
      fullPath: '/api/agent/keys'
      preLoaderRoute: typeof ApiAgentKeysRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/locks': {
      id: '/api/agent/locks'
      path: '/locks'
      fullPath: '/api/agent/locks'
      preLoaderRoute: typeof ApiAgentLocksRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/mcp': {
      id: '/api/agent/mcp'
      path: '/mcp'
      fullPath: '/api/agent/mcp'
      preLoaderRoute: typeof ApiAgentMcpRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/notices': {
      id: '/api/agent/notices'
      path: '/notices'
      fullPath: '/api/agent/notices'
      preLoaderRoute: typeof ApiAgentNoticesRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/openai': {
      id: '/api/agent/openai'
      path: '/openai'
      fullPath: '/api/agent/openai'
      preLoaderRoute: typeof ApiAgentOpenaiRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/openapi': {
      id: '/api/agent/openapi'
      path: '/openapi'
      fullPath: '/api/agent/openapi'
      preLoaderRoute: typeof ApiAgentOpenapiRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/ping': {
      id: '/api/agent/ping'
      path: '/ping'
      fullPath: '/api/agent/ping'
      preLoaderRoute: typeof ApiAgentPingRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/pred': {
      id: '/api/agent/pred'
      path: '/pred'
      fullPath: '/api/agent/pred'
      preLoaderRoute: typeof ApiAgentPredRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/roadmap': {
      id: '/api/agent/roadmap'
      path: '/roadmap'
      fullPath: '/api/agent/roadmap'
      preLoaderRoute: typeof ApiAgentRoadmapRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/siri': {
      id: '/api/agent/siri'
      path: '/siri'
      fullPath: '/api/agent/siri'
      preLoaderRoute: typeof ApiAgentSiriRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/waitlist': {
      id: '/api/agent/waitlist'
      path: '/waitlist'
      fullPath: '/api/agent/waitlist'
      preLoaderRoute: typeof ApiAgentWaitlistRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/webmcp': {
      id: '/api/agent/webmcp'
      path: '/webmcp'
      fullPath: '/api/agent/webmcp'
      preLoaderRoute: typeof ApiAgentWebmcpRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/board/pic/$id': {
      id: '/api/agent/board/pic/$id'
      path: '/pic/$id'
      fullPath: '/api/agent/board/pic/$id'
      preLoaderRoute: typeof ApiAgentBoardPicIdRouteImport
      parentRoute: typeof ApiAgentBoardRoute
    }
  }
}

interface BoardRouteChildren {
  BoardIdRoute: typeof BoardIdRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardIdRoute: BoardIdRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

interface ApiAgentBoardRouteChildren {
  ApiAgentBoardPicIdRoute: typeof ApiAgentBoardPicIdRoute
}

const ApiAgentBoardRouteChildren: ApiAgentBoardRouteChildren = {
  ApiAgentBoardPicIdRoute: ApiAgentBoardPicIdRoute,
}

const ApiAgentBoardRouteWithChildren = ApiAgentBoardRoute._addFileChildren(
  ApiAgentBoardRouteChildren,
)

interface ApiAgentRouteChildren {
  ApiAgentA2aRoute: typeof ApiAgentA2aRoute
  ApiAgentAppRoute: typeof ApiAgentAppRoute
  ApiAgentAppleRoute: typeof ApiAgentAppleRoute
  ApiAgentBoardRoute: typeof ApiAgentBoardRouteWithChildren
  ApiAgentCallRoute: typeof ApiAgentCallRoute
  ApiAgentCardRoute: typeof ApiAgentCardRoute
  ApiAgentClaudeRoute: typeof ApiAgentClaudeRoute
  ApiAgentConnectRoute: typeof ApiAgentConnectRoute
  ApiAgentCupRoute: typeof ApiAgentCupRoute
  ApiAgentFeeRoute: typeof ApiAgentFeeRoute
  ApiAgentForumRoute: typeof ApiAgentForumRoute
  ApiAgentGoogleRoute: typeof ApiAgentGoogleRoute
  ApiAgentGrokRoute: typeof ApiAgentGrokRoute
  ApiAgentHiveRoute: typeof ApiAgentHiveRoute
  ApiAgentKeysRoute: typeof ApiAgentKeysRoute
  ApiAgentLocksRoute: typeof ApiAgentLocksRoute
  ApiAgentMcpRoute: typeof ApiAgentMcpRoute
  ApiAgentNoticesRoute: typeof ApiAgentNoticesRoute
  ApiAgentOpenaiRoute: typeof ApiAgentOpenaiRoute
  ApiAgentOpenapiRoute: typeof ApiAgentOpenapiRoute
  ApiAgentPingRoute: typeof ApiAgentPingRoute
  ApiAgentPredRoute: typeof ApiAgentPredRoute
  ApiAgentRoadmapRoute: typeof ApiAgentRoadmapRoute
  ApiAgentSiriRoute: typeof ApiAgentSiriRoute
  ApiAgentWaitlistRoute: typeof ApiAgentWaitlistRoute
  ApiAgentWebmcpRoute: typeof ApiAgentWebmcpRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentA2aRoute: ApiAgentA2aRoute,
  ApiAgentAppRoute: ApiAgentAppRoute,
  ApiAgentAppleRoute: ApiAgentAppleRoute,
  ApiAgentBoardRoute: ApiAgentBoardRouteWithChildren,
  ApiAgentCallRoute: ApiAgentCallRoute,
  ApiAgentCardRoute: ApiAgentCardRoute,
  ApiAgentClaudeRoute: ApiAgentClaudeRoute,
  ApiAgentConnectRoute: ApiAgentConnectRoute,
  ApiAgentCupRoute: ApiAgentCupRoute,
  ApiAgentFeeRoute: ApiAgentFeeRoute,
  ApiAgentForumRoute: ApiAgentForumRoute,
  ApiAgentGoogleRoute: ApiAgentGoogleRoute,
  ApiAgentGrokRoute: ApiAgentGrokRoute,
  ApiAgentHiveRoute: ApiAgentHiveRoute,
  ApiAgentKeysRoute: ApiAgentKeysRoute,
  ApiAgentLocksRoute: ApiAgentLocksRoute,
  ApiAgentMcpRoute: ApiAgentMcpRoute,
  ApiAgentNoticesRoute: ApiAgentNoticesRoute,
  ApiAgentOpenaiRoute: ApiAgentOpenaiRoute,
  ApiAgentOpenapiRoute: ApiAgentOpenapiRoute,
  ApiAgentPingRoute: ApiAgentPingRoute,
  ApiAgentPredRoute: ApiAgentPredRoute,
  ApiAgentRoadmapRoute: ApiAgentRoadmapRoute,
  ApiAgentSiriRoute: ApiAgentSiriRoute,
  ApiAgentWaitlistRoute: ApiAgentWaitlistRoute,
  ApiAgentWebmcpRoute: ApiAgentWebmcpRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  AiCatalogDotjsonRoute: AiCatalogDotjsonRoute,
  AppRoute: AppRoute,
  B3arsRoute: B3arsRoute,
  BoardRoute: BoardRouteWithChildren,
  BowlRoute: BowlRoute,
  C0ff33Route: C0ff33Route,
  C0utRoute: C0utRoute,
  CoffeeRoute: CoffeeRoute,
  ComputeRoute: ComputeRoute,
  CupRoute: CupRoute,
  EntityDotjsonRoute: EntityDotjsonRoute,
  F33dRoute: F33dRoute,
  FaqRoute: FaqRoute,
  ForumRoute: ForumRoute,
  GmRoute: GmRoute,
  GuideRoute: GuideRoute,
  H1v3Route: H1v3Route,
  HeliosRoute: HeliosRoute,
  HeliosbotRoute: HeliosbotRoute,
  HiveRoute: HiveRoute,
  IosRoute: IosRoute,
  L0ckRoute: L0ckRoute,
  LaunchRoute: LaunchRoute,
  LockRoute: LockRoute,
  Lock3dRoute: Lock3dRoute,
  LoginRoute: LoginRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  MediaRoute: MediaRoute,
  OssRoadmapRoute: OssRoadmapRoute,
  OwlRoute: OwlRoute,
  PlayRoute: PlayRoute,
  Pr3dRoute: Pr3dRoute,
  PredRoute: PredRoute,
  PredictionsRoute: PredictionsRoute,
  PrivacyRoute: PrivacyRoute,
  R0b0tsRoute: R0b0tsRoute,
  RenewRoute: RenewRoute,
  RoadmapRoute: RoadmapRoute,
  S1r1usRoute: S1r1usRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  SimRoute: SimRoute,
  SitemapRoute: SitemapRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourceRoute: SourceRoute,
  SwarmRoute: SwarmRoute,
  TermsRoute: TermsRoute,
  ThemeRoute: ThemeRoute,
  VideoSitemapDotxmlRoute: VideoSitemapDotxmlRoute,
  W0rldRoute: W0rldRoute,
  Wh1t3Route: Wh1t3Route,
  WorldCupRoute: WorldCupRoute,
  DotwellKnownAgentCardDotjsonRoute: DotwellKnownAgentCardDotjsonRoute,
  DotwellKnownAgentDotjsonRoute: DotwellKnownAgentDotjsonRoute,
  DotwellKnownAiCatalogDotjsonRoute: DotwellKnownAiCatalogDotjsonRoute,
  DotwellKnownAiPluginDotjsonRoute: DotwellKnownAiPluginDotjsonRoute,
  DotwellKnownAppleAppSiteAssociationRoute:
    DotwellKnownAppleAppSiteAssociationRoute,
  DotwellKnownAssetlinksDotjsonRoute: DotwellKnownAssetlinksDotjsonRoute,
  DotwellKnownLlmsDottxtRoute: DotwellKnownLlmsDottxtRoute,
  DotwellKnownMcpServerDotjsonRoute: DotwellKnownMcpServerDotjsonRoute,
  DotwellKnownMcpDotjsonRoute: DotwellKnownMcpDotjsonRoute,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  AppAdminRoute: AppAdminRoute,
  MorningPdfIdRoute: MorningPdfIdRoute,
  DotwellKnownMcpServerCardDotjsonRoute: DotwellKnownMcpServerCardDotjsonRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
