/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as F33dRouteImport } from './routes/f33d'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GmRouteImport } from './routes/gm'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HeliosRouteImport } from './routes/helios'
import { Route as HeliosbotRouteImport } from './routes/heliosbot'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as S1r1usRouteImport } from './routes/s1r1us'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SourceRouteImport } from './routes/source'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as ApiAgentCallRouteImport } from './routes/api/agent/call'
import { Route as ApiAgentPingRouteImport } from './routes/api/agent.ping'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const F33dRoute = F33dRouteImport.update({
  id: '/f33d',
  path: '/f33d',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GmRoute = GmRouteImport.update({
  id: '/gm',
  path: '/gm',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HeliosRoute = HeliosRouteImport.update({
  id: '/helios',
  path: '/helios',
  getParentRoute: () => rootRouteImport,
} as any)
const HeliosbotRoute = HeliosbotRouteImport.update({
  id: '/heliosbot',
  path: '/heliosbot',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const S1r1usRoute = S1r1usRouteImport.update({
  id: '/s1r1us',
  path: '/s1r1us',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentCallRoute = ApiAgentCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentPingRoute = ApiAgentPingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/f33d': typeof F33dRoute
  '/faq': typeof FaqRoute
  '/gm': typeof GmRoute
  '/guide': typeof GuideRoute
  '/helios': typeof HeliosRoute
  '/heliosbot': typeof HeliosbotRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/renew': typeof RenewRoute
  '/s1r1us': typeof S1r1usRoute
  '/security': typeof SecurityRoute
  '/sitemap': typeof SitemapRoute
  '/source': typeof SourceRoute
  '/terms': typeof TermsRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/agent/call': typeof ApiAgentCallRoute
  '/api/agent/ping': typeof ApiAgentPingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/f33d': typeof F33dRoute
  '/faq': typeof FaqRoute
  '/gm': typeof GmRoute
  '/guide': typeof GuideRoute
  '/helios': typeof HeliosRoute
  '/heliosbot': typeof HeliosbotRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/renew': typeof RenewRoute
  '/s1r1us': typeof S1r1usRoute
  '/security': typeof SecurityRoute
  '/sitemap': typeof SitemapRoute
  '/source': typeof SourceRoute
  '/terms': typeof TermsRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/agent/call': typeof ApiAgentCallRoute
  '/api/agent/ping': typeof ApiAgentPingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/f33d': typeof F33dRoute
  '/faq': typeof FaqRoute
  '/gm': typeof GmRoute
  '/guide': typeof GuideRoute
  '/helios': typeof HeliosRoute
  '/heliosbot': typeof HeliosbotRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/renew': typeof RenewRoute
  '/s1r1us': typeof S1r1usRoute
  '/security': typeof SecurityRoute
  '/sitemap': typeof SitemapRoute
  '/source': typeof SourceRoute
  '/terms': typeof TermsRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/agent/call': typeof ApiAgentCallRoute
  '/api/agent/ping': typeof ApiAgentPingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/f33d'
    | '/faq'
    | '/gm'
    | '/guide'
    | '/helios'
    | '/heliosbot'
    | '/launch'
    | '/login'
    | '/renew'
    | '/s1r1us'
    | '/security'
    | '/sitemap'
    | '/source'
    | '/terms'
    | '/api/agent'
    | '/api/agent/call'
    | '/api/agent/ping'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/f33d'
    | '/faq'
    | '/gm'
    | '/guide'
    | '/helios'
    | '/heliosbot'
    | '/launch'
    | '/login'
    | '/renew'
    | '/s1r1us'
    | '/security'
    | '/sitemap'
    | '/source'
    | '/terms'
    | '/api/agent'
    | '/api/agent/call'
    | '/api/agent/ping'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/f33d'
    | '/faq'
    | '/gm'
    | '/guide'
    | '/helios'
    | '/heliosbot'
    | '/launch'
    | '/login'
    | '/renew'
    | '/s1r1us'
    | '/security'
    | '/sitemap'
    | '/source'
    | '/terms'
    | '/api/agent'
    | '/api/agent/call'
    | '/api/agent/ping'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  F33dRoute: typeof F33dRoute
  FaqRoute: typeof FaqRoute
  GmRoute: typeof GmRoute
  GuideRoute: typeof GuideRoute
  HeliosRoute: typeof HeliosRoute
  HeliosbotRoute: typeof HeliosbotRoute
  LaunchRoute: typeof LaunchRoute
  LoginRoute: typeof LoginRoute
  RenewRoute: typeof RenewRoute
  S1r1usRoute: typeof S1r1usRoute
  SecurityRoute: typeof SecurityRoute
  SitemapRoute: typeof SitemapRoute
  SourceRoute: typeof SourceRoute
  TermsRoute: typeof TermsRoute
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f33d': {
      id: '/f33d'
      path: '/f33d'
      fullPath: '/f33d'
      preLoaderRoute: typeof F33dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm': {
      id: '/gm'
      path: '/gm'
      fullPath: '/gm'
      preLoaderRoute: typeof GmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helios': {
      id: '/helios'
      path: '/helios'
      fullPath: '/helios'
      preLoaderRoute: typeof HeliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heliosbot': {
      id: '/heliosbot'
      path: '/heliosbot'
      fullPath: '/heliosbot'
      preLoaderRoute: typeof HeliosbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s1r1us': {
      id: '/s1r1us'
      path: '/s1r1us'
      fullPath: '/s1r1us'
      preLoaderRoute: typeof S1r1usRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/call': {
      id: '/api/agent/call'
      path: '/call'
      fullPath: '/api/agent/call'
      preLoaderRoute: typeof ApiAgentCallRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/ping': {
      id: '/api/agent/ping'
      path: '/ping'
      fullPath: '/api/agent/ping'
      preLoaderRoute: typeof ApiAgentPingRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAgentRouteChildren {
  ApiAgentCallRoute: typeof ApiAgentCallRoute
  ApiAgentPingRoute: typeof ApiAgentPingRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentCallRoute: ApiAgentCallRoute,
  ApiAgentPingRoute: ApiAgentPingRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  F33dRoute: F33dRoute,
  FaqRoute: FaqRoute,
  GmRoute: GmRoute,
  GuideRoute: GuideRoute,
  HeliosRoute: HeliosRoute,
  HeliosbotRoute: HeliosbotRoute,
  LaunchRoute: LaunchRoute,
  LoginRoute: LoginRoute,
  RenewRoute: RenewRoute,
  S1r1usRoute: S1r1usRoute,
  SecurityRoute: SecurityRoute,
  SitemapRoute: SitemapRoute,
  SourceRoute: SourceRoute,
  TermsRoute: TermsRoute,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
