/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as B3arsRouteImport } from './routes/b3ars'
import { Route as C0ff33RouteImport } from './routes/c0ff33'
import { Route as CoffeeRouteImport } from './routes/coffee'
import { Route as ComputeRouteImport } from './routes/compute'
import { Route as EntityDotjsonRouteImport } from './routes/entity[.]json'
import { Route as F33dRouteImport } from './routes/f33d'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as GmRouteImport } from './routes/gm'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HeliosRouteImport } from './routes/helios'
import { Route as HeliosbotRouteImport } from './routes/heliosbot'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MediaRouteImport } from './routes/media'
import { Route as OwlRouteImport } from './routes/owl'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as R0b0tsRouteImport } from './routes/r0b0ts'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as S1r1usRouteImport } from './routes/s1r1us'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SourceRouteImport } from './routes/source'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as VideoSitemapDotxmlRouteImport } from './routes/video-sitemap[.]xml'
import { Route as DotwellKnownAgentCardDotjsonRouteImport } from './routes/[.]well-known/agent-card[.]json'
import { Route as DotwellKnownAgentDotjsonRouteImport } from './routes/[.]well-known/agent[.]json'
import { Route as DotwellKnownAiPluginDotjsonRouteImport } from './routes/[.]well-known/ai-plugin[.]json'
import { Route as ApiAgentRouteImport } from './routes/api.agent'
import { Route as MorningPdfIdRouteImport } from './routes/morning-pdf.$id'
import { Route as ApiAgentA2aRouteImport } from './routes/api/agent.a2a'
import { Route as ApiAgentCallRouteImport } from './routes/api/agent/call'
import { Route as ApiAgentCardRouteImport } from './routes/api/agent.card'
import { Route as ApiAgentClaudeRouteImport } from './routes/api/agent.claude'
import { Route as ApiAgentFeeRouteImport } from './routes/api/agent.fee'
import { Route as ApiAgentForumRouteImport } from './routes/api/agent.forum'
import { Route as ApiAgentGrokRouteImport } from './routes/api/agent.grok'
import { Route as ApiAgentKeysRouteImport } from './routes/api/agent.keys'
import { Route as ApiAgentMcpRouteImport } from './routes/api/agent.mcp'
import { Route as ApiAgentNoticesRouteImport } from './routes/api/agent.notices'
import { Route as ApiAgentOpenaiRouteImport } from './routes/api/agent.openai'
import { Route as ApiAgentOpenapiRouteImport } from './routes/api/agent.openapi'
import { Route as ApiAgentPingRouteImport } from './routes/api/agent.ping'
import { Route as ApiAgentWaitlistRouteImport } from './routes/api/agent.waitlist'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const B3arsRoute = B3arsRouteImport.update({
  id: '/b3ars',
  path: '/b3ars',
  getParentRoute: () => rootRouteImport,
} as any)
const C0ff33Route = C0ff33RouteImport.update({
  id: '/c0ff33',
  path: '/c0ff33',
  getParentRoute: () => rootRouteImport,
} as any)
const CoffeeRoute = CoffeeRouteImport.update({
  id: '/coffee',
  path: '/coffee',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputeRoute = ComputeRouteImport.update({
  id: '/compute',
  path: '/compute',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityDotjsonRoute = EntityDotjsonRouteImport.update({
  id: '/entity.json',
  path: '/entity.json',
  getParentRoute: () => rootRouteImport,
} as any)
const F33dRoute = F33dRouteImport.update({
  id: '/f33d',
  path: '/f33d',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const GmRoute = GmRouteImport.update({
  id: '/gm',
  path: '/gm',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HeliosRoute = HeliosRouteImport.update({
  id: '/helios',
  path: '/helios',
  getParentRoute: () => rootRouteImport,
} as any)
const HeliosbotRoute = HeliosbotRouteImport.update({
  id: '/heliosbot',
  path: '/heliosbot',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const OwlRoute = OwlRouteImport.update({
  id: '/owl',
  path: '/owl',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const R0b0tsRoute = R0b0tsRouteImport.update({
  id: '/r0b0ts',
  path: '/r0b0ts',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const S1r1usRoute = S1r1usRouteImport.update({
  id: '/s1r1us',
  path: '/s1r1us',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRoute = SourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoSitemapDotxmlRoute = VideoSitemapDotxmlRouteImport.update({
  id: '/video-sitemap.xml',
  path: '/video-sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentCardDotjsonRoute =
  DotwellKnownAgentCardDotjsonRouteImport.update({
    id: '/.well-known/agent-card.json',
    path: '/.well-known/agent-card.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAgentDotjsonRoute =
  DotwellKnownAgentDotjsonRouteImport.update({
    id: '/.well-known/agent.json',
    path: '/.well-known/agent.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownAiPluginDotjsonRoute =
  DotwellKnownAiPluginDotjsonRouteImport.update({
    id: '/.well-known/ai-plugin.json',
    path: '/.well-known/ai-plugin.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const MorningPdfIdRoute = MorningPdfIdRouteImport.update({
  id: '/morning-pdf/$id',
  path: '/morning-pdf/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentA2aRoute = ApiAgentA2aRouteImport.update({
  id: '/a2a',
  path: '/a2a',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentCallRoute = ApiAgentCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentCardRoute = ApiAgentCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentClaudeRoute = ApiAgentClaudeRouteImport.update({
  id: '/claude',
  path: '/claude',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentFeeRoute = ApiAgentFeeRouteImport.update({
  id: '/fee',
  path: '/fee',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentForumRoute = ApiAgentForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentGrokRoute = ApiAgentGrokRouteImport.update({
  id: '/grok',
  path: '/grok',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentKeysRoute = ApiAgentKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentMcpRoute = ApiAgentMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentNoticesRoute = ApiAgentNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentOpenaiRoute = ApiAgentOpenaiRouteImport.update({
  id: '/openai',
  path: '/openai',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentOpenapiRoute = ApiAgentOpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentPingRoute = ApiAgentPingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAgentWaitlistRoute = ApiAgentWaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/b3ars': typeof B3arsRoute
  '/c0ff33': typeof C0ff33Route
  '/coffee': typeof CoffeeRoute
  '/compute': typeof ComputeRoute
  '/entity.json': typeof EntityDotjsonRoute
  '/f33d': typeof F33dRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/gm': typeof GmRoute
  '/guide': typeof GuideRoute
  '/helios': typeof HeliosRoute
  '/heliosbot': typeof HeliosbotRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/owl': typeof OwlRoute
  '/privacy': typeof PrivacyRoute
  '/r0b0ts': typeof R0b0tsRoute
  '/renew': typeof RenewRoute
  '/s1r1us': typeof S1r1usRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/terms': typeof TermsRoute
  '/theme': typeof ThemeRoute
  '/video-sitemap.xml': typeof VideoSitemapDotxmlRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/ai-plugin.json': typeof DotwellKnownAiPluginDotjsonRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/morning-pdf/$id': typeof MorningPdfIdRoute
  '/api/agent/a2a': typeof ApiAgentA2aRoute
  '/api/agent/call': typeof ApiAgentCallRoute
  '/api/agent/card': typeof ApiAgentCardRoute
  '/api/agent/claude': typeof ApiAgentClaudeRoute
  '/api/agent/fee': typeof ApiAgentFeeRoute
  '/api/agent/forum': typeof ApiAgentForumRoute
  '/api/agent/grok': typeof ApiAgentGrokRoute
  '/api/agent/keys': typeof ApiAgentKeysRoute
  '/api/agent/mcp': typeof ApiAgentMcpRoute
  '/api/agent/notices': typeof ApiAgentNoticesRoute
  '/api/agent/openai': typeof ApiAgentOpenaiRoute
  '/api/agent/openapi': typeof ApiAgentOpenapiRoute
  '/api/agent/ping': typeof ApiAgentPingRoute
  '/api/agent/waitlist': typeof ApiAgentWaitlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/b3ars': typeof B3arsRoute
  '/c0ff33': typeof C0ff33Route
  '/coffee': typeof CoffeeRoute
  '/compute': typeof ComputeRoute
  '/entity.json': typeof EntityDotjsonRoute
  '/f33d': typeof F33dRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/gm': typeof GmRoute
  '/guide': typeof GuideRoute
  '/helios': typeof HeliosRoute
  '/heliosbot': typeof HeliosbotRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/owl': typeof OwlRoute
  '/privacy': typeof PrivacyRoute
  '/r0b0ts': typeof R0b0tsRoute
  '/renew': typeof RenewRoute
  '/s1r1us': typeof S1r1usRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/terms': typeof TermsRoute
  '/theme': typeof ThemeRoute
  '/video-sitemap.xml': typeof VideoSitemapDotxmlRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/ai-plugin.json': typeof DotwellKnownAiPluginDotjsonRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/morning-pdf/$id': typeof MorningPdfIdRoute
  '/api/agent/a2a': typeof ApiAgentA2aRoute
  '/api/agent/call': typeof ApiAgentCallRoute
  '/api/agent/card': typeof ApiAgentCardRoute
  '/api/agent/claude': typeof ApiAgentClaudeRoute
  '/api/agent/fee': typeof ApiAgentFeeRoute
  '/api/agent/forum': typeof ApiAgentForumRoute
  '/api/agent/grok': typeof ApiAgentGrokRoute
  '/api/agent/keys': typeof ApiAgentKeysRoute
  '/api/agent/mcp': typeof ApiAgentMcpRoute
  '/api/agent/notices': typeof ApiAgentNoticesRoute
  '/api/agent/openai': typeof ApiAgentOpenaiRoute
  '/api/agent/openapi': typeof ApiAgentOpenapiRoute
  '/api/agent/ping': typeof ApiAgentPingRoute
  '/api/agent/waitlist': typeof ApiAgentWaitlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agent': typeof AgentRoute
  '/b3ars': typeof B3arsRoute
  '/c0ff33': typeof C0ff33Route
  '/coffee': typeof CoffeeRoute
  '/compute': typeof ComputeRoute
  '/entity.json': typeof EntityDotjsonRoute
  '/f33d': typeof F33dRoute
  '/faq': typeof FaqRoute
  '/forum': typeof ForumRoute
  '/gm': typeof GmRoute
  '/guide': typeof GuideRoute
  '/helios': typeof HeliosRoute
  '/heliosbot': typeof HeliosbotRoute
  '/launch': typeof LaunchRoute
  '/login': typeof LoginRoute
  '/media': typeof MediaRoute
  '/owl': typeof OwlRoute
  '/privacy': typeof PrivacyRoute
  '/r0b0ts': typeof R0b0tsRoute
  '/renew': typeof RenewRoute
  '/s1r1us': typeof S1r1usRoute
  '/search': typeof SearchRoute
  '/security': typeof SecurityRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/source': typeof SourceRoute
  '/terms': typeof TermsRoute
  '/theme': typeof ThemeRoute
  '/video-sitemap.xml': typeof VideoSitemapDotxmlRoute
  '/.well-known/agent-card.json': typeof DotwellKnownAgentCardDotjsonRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/.well-known/ai-plugin.json': typeof DotwellKnownAiPluginDotjsonRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/morning-pdf/$id': typeof MorningPdfIdRoute
  '/api/agent/a2a': typeof ApiAgentA2aRoute
  '/api/agent/call': typeof ApiAgentCallRoute
  '/api/agent/card': typeof ApiAgentCardRoute
  '/api/agent/claude': typeof ApiAgentClaudeRoute
  '/api/agent/fee': typeof ApiAgentFeeRoute
  '/api/agent/forum': typeof ApiAgentForumRoute
  '/api/agent/grok': typeof ApiAgentGrokRoute
  '/api/agent/keys': typeof ApiAgentKeysRoute
  '/api/agent/mcp': typeof ApiAgentMcpRoute
  '/api/agent/notices': typeof ApiAgentNoticesRoute
  '/api/agent/openai': typeof ApiAgentOpenaiRoute
  '/api/agent/openapi': typeof ApiAgentOpenapiRoute
  '/api/agent/ping': typeof ApiAgentPingRoute
  '/api/agent/waitlist': typeof ApiAgentWaitlistRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agent'
    | '/b3ars'
    | '/c0ff33'
    | '/coffee'
    | '/compute'
    | '/entity.json'
    | '/f33d'
    | '/faq'
    | '/forum'
    | '/gm'
    | '/guide'
    | '/helios'
    | '/heliosbot'
    | '/launch'
    | '/login'
    | '/media'
    | '/owl'
    | '/privacy'
    | '/r0b0ts'
    | '/renew'
    | '/s1r1us'
    | '/search'
    | '/security'
    | '/sitemap'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/source'
    | '/terms'
    | '/theme'
    | '/video-sitemap.xml'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/ai-plugin.json'
    | '/api/agent'
    | '/morning-pdf/$id'
    | '/api/agent/a2a'
    | '/api/agent/call'
    | '/api/agent/card'
    | '/api/agent/claude'
    | '/api/agent/fee'
    | '/api/agent/forum'
    | '/api/agent/grok'
    | '/api/agent/keys'
    | '/api/agent/mcp'
    | '/api/agent/notices'
    | '/api/agent/openai'
    | '/api/agent/openapi'
    | '/api/agent/ping'
    | '/api/agent/waitlist'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agent'
    | '/b3ars'
    | '/c0ff33'
    | '/coffee'
    | '/compute'
    | '/entity.json'
    | '/f33d'
    | '/faq'
    | '/forum'
    | '/gm'
    | '/guide'
    | '/helios'
    | '/heliosbot'
    | '/launch'
    | '/login'
    | '/media'
    | '/owl'
    | '/privacy'
    | '/r0b0ts'
    | '/renew'
    | '/s1r1us'
    | '/search'
    | '/security'
    | '/sitemap'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/source'
    | '/terms'
    | '/theme'
    | '/video-sitemap.xml'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/ai-plugin.json'
    | '/api/agent'
    | '/morning-pdf/$id'
    | '/api/agent/a2a'
    | '/api/agent/call'
    | '/api/agent/card'
    | '/api/agent/claude'
    | '/api/agent/fee'
    | '/api/agent/forum'
    | '/api/agent/grok'
    | '/api/agent/keys'
    | '/api/agent/mcp'
    | '/api/agent/notices'
    | '/api/agent/openai'
    | '/api/agent/openapi'
    | '/api/agent/ping'
    | '/api/agent/waitlist'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agent'
    | '/b3ars'
    | '/c0ff33'
    | '/coffee'
    | '/compute'
    | '/entity.json'
    | '/f33d'
    | '/faq'
    | '/forum'
    | '/gm'
    | '/guide'
    | '/helios'
    | '/heliosbot'
    | '/launch'
    | '/login'
    | '/media'
    | '/owl'
    | '/privacy'
    | '/r0b0ts'
    | '/renew'
    | '/s1r1us'
    | '/search'
    | '/security'
    | '/sitemap'
    | '/sitemap-index.xml'
    | '/sitemap.xml'
    | '/source'
    | '/terms'
    | '/theme'
    | '/video-sitemap.xml'
    | '/.well-known/agent-card.json'
    | '/.well-known/agent.json'
    | '/.well-known/ai-plugin.json'
    | '/api/agent'
    | '/morning-pdf/$id'
    | '/api/agent/a2a'
    | '/api/agent/call'
    | '/api/agent/card'
    | '/api/agent/claude'
    | '/api/agent/fee'
    | '/api/agent/forum'
    | '/api/agent/grok'
    | '/api/agent/keys'
    | '/api/agent/mcp'
    | '/api/agent/notices'
    | '/api/agent/openai'
    | '/api/agent/openapi'
    | '/api/agent/ping'
    | '/api/agent/waitlist'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgentRoute: typeof AgentRoute
  B3arsRoute: typeof B3arsRoute
  C0ff33Route: typeof C0ff33Route
  CoffeeRoute: typeof CoffeeRoute
  ComputeRoute: typeof ComputeRoute
  EntityDotjsonRoute: typeof EntityDotjsonRoute
  F33dRoute: typeof F33dRoute
  FaqRoute: typeof FaqRoute
  ForumRoute: typeof ForumRoute
  GmRoute: typeof GmRoute
  GuideRoute: typeof GuideRoute
  HeliosRoute: typeof HeliosRoute
  HeliosbotRoute: typeof HeliosbotRoute
  LaunchRoute: typeof LaunchRoute
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRoute
  OwlRoute: typeof OwlRoute
  PrivacyRoute: typeof PrivacyRoute
  R0b0tsRoute: typeof R0b0tsRoute
  RenewRoute: typeof RenewRoute
  S1r1usRoute: typeof S1r1usRoute
  SearchRoute: typeof SearchRoute
  SecurityRoute: typeof SecurityRoute
  SitemapRoute: typeof SitemapRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SourceRoute: typeof SourceRoute
  TermsRoute: typeof TermsRoute
  ThemeRoute: typeof ThemeRoute
  VideoSitemapDotxmlRoute: typeof VideoSitemapDotxmlRoute
  DotwellKnownAgentCardDotjsonRoute: typeof DotwellKnownAgentCardDotjsonRoute
  DotwellKnownAgentDotjsonRoute: typeof DotwellKnownAgentDotjsonRoute
  DotwellKnownAiPluginDotjsonRoute: typeof DotwellKnownAiPluginDotjsonRoute
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  MorningPdfIdRoute: typeof MorningPdfIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b3ars': {
      id: '/b3ars'
      path: '/b3ars'
      fullPath: '/b3ars'
      preLoaderRoute: typeof B3arsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c0ff33': {
      id: '/c0ff33'
      path: '/c0ff33'
      fullPath: '/c0ff33'
      preLoaderRoute: typeof C0ff33RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coffee': {
      id: '/coffee'
      path: '/coffee'
      fullPath: '/coffee'
      preLoaderRoute: typeof CoffeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compute': {
      id: '/compute'
      path: '/compute'
      fullPath: '/compute'
      preLoaderRoute: typeof ComputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity.json': {
      id: '/entity.json'
      path: '/entity.json'
      fullPath: '/entity.json'
      preLoaderRoute: typeof EntityDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f33d': {
      id: '/f33d'
      path: '/f33d'
      fullPath: '/f33d'
      preLoaderRoute: typeof F33dRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm': {
      id: '/gm'
      path: '/gm'
      fullPath: '/gm'
      preLoaderRoute: typeof GmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helios': {
      id: '/helios'
      path: '/helios'
      fullPath: '/helios'
      preLoaderRoute: typeof HeliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heliosbot': {
      id: '/heliosbot'
      path: '/heliosbot'
      fullPath: '/heliosbot'
      preLoaderRoute: typeof HeliosbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owl': {
      id: '/owl'
      path: '/owl'
      fullPath: '/owl'
      preLoaderRoute: typeof OwlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r0b0ts': {
      id: '/r0b0ts'
      path: '/r0b0ts'
      fullPath: '/r0b0ts'
      preLoaderRoute: typeof R0b0tsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s1r1us': {
      id: '/s1r1us'
      path: '/s1r1us'
      fullPath: '/s1r1us'
      preLoaderRoute: typeof S1r1usRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source': {
      id: '/source'
      path: '/source'
      fullPath: '/source'
      preLoaderRoute: typeof SourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-sitemap.xml': {
      id: '/video-sitemap.xml'
      path: '/video-sitemap.xml'
      fullPath: '/video-sitemap.xml'
      preLoaderRoute: typeof VideoSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-card.json': {
      id: '/.well-known/agent-card.json'
      path: '/.well-known/agent-card.json'
      fullPath: '/.well-known/agent-card.json'
      preLoaderRoute: typeof DotwellKnownAgentCardDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent.json': {
      id: '/.well-known/agent.json'
      path: '/.well-known/agent.json'
      fullPath: '/.well-known/agent.json'
      preLoaderRoute: typeof DotwellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/ai-plugin.json': {
      id: '/.well-known/ai-plugin.json'
      path: '/.well-known/ai-plugin.json'
      fullPath: '/.well-known/ai-plugin.json'
      preLoaderRoute: typeof DotwellKnownAiPluginDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morning-pdf/$id': {
      id: '/morning-pdf/$id'
      path: '/morning-pdf/$id'
      fullPath: '/morning-pdf/$id'
      preLoaderRoute: typeof MorningPdfIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/a2a': {
      id: '/api/agent/a2a'
      path: '/a2a'
      fullPath: '/api/agent/a2a'
      preLoaderRoute: typeof ApiAgentA2aRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/call': {
      id: '/api/agent/call'
      path: '/call'
      fullPath: '/api/agent/call'
      preLoaderRoute: typeof ApiAgentCallRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/card': {
      id: '/api/agent/card'
      path: '/card'
      fullPath: '/api/agent/card'
      preLoaderRoute: typeof ApiAgentCardRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/claude': {
      id: '/api/agent/claude'
      path: '/claude'
      fullPath: '/api/agent/claude'
      preLoaderRoute: typeof ApiAgentClaudeRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/fee': {
      id: '/api/agent/fee'
      path: '/fee'
      fullPath: '/api/agent/fee'
      preLoaderRoute: typeof ApiAgentFeeRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/forum': {
      id: '/api/agent/forum'
      path: '/forum'
      fullPath: '/api/agent/forum'
      preLoaderRoute: typeof ApiAgentForumRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/grok': {
      id: '/api/agent/grok'
      path: '/grok'
      fullPath: '/api/agent/grok'
      preLoaderRoute: typeof ApiAgentGrokRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/keys': {
      id: '/api/agent/keys'
      path: '/keys'
      fullPath: '/api/agent/keys'
      preLoaderRoute: typeof ApiAgentKeysRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/mcp': {
      id: '/api/agent/mcp'
      path: '/mcp'
      fullPath: '/api/agent/mcp'
      preLoaderRoute: typeof ApiAgentMcpRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/notices': {
      id: '/api/agent/notices'
      path: '/notices'
      fullPath: '/api/agent/notices'
      preLoaderRoute: typeof ApiAgentNoticesRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/openai': {
      id: '/api/agent/openai'
      path: '/openai'
      fullPath: '/api/agent/openai'
      preLoaderRoute: typeof ApiAgentOpenaiRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/openapi': {
      id: '/api/agent/openapi'
      path: '/openapi'
      fullPath: '/api/agent/openapi'
      preLoaderRoute: typeof ApiAgentOpenapiRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/ping': {
      id: '/api/agent/ping'
      path: '/ping'
      fullPath: '/api/agent/ping'
      preLoaderRoute: typeof ApiAgentPingRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/agent/waitlist': {
      id: '/api/agent/waitlist'
      path: '/waitlist'
      fullPath: '/api/agent/waitlist'
      preLoaderRoute: typeof ApiAgentWaitlistRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAgentRouteChildren {
  ApiAgentA2aRoute: typeof ApiAgentA2aRoute
  ApiAgentCallRoute: typeof ApiAgentCallRoute
  ApiAgentCardRoute: typeof ApiAgentCardRoute
  ApiAgentClaudeRoute: typeof ApiAgentClaudeRoute
  ApiAgentFeeRoute: typeof ApiAgentFeeRoute
  ApiAgentForumRoute: typeof ApiAgentForumRoute
  ApiAgentGrokRoute: typeof ApiAgentGrokRoute
  ApiAgentKeysRoute: typeof ApiAgentKeysRoute
  ApiAgentMcpRoute: typeof ApiAgentMcpRoute
  ApiAgentNoticesRoute: typeof ApiAgentNoticesRoute
  ApiAgentOpenaiRoute: typeof ApiAgentOpenaiRoute
  ApiAgentOpenapiRoute: typeof ApiAgentOpenapiRoute
  ApiAgentPingRoute: typeof ApiAgentPingRoute
  ApiAgentWaitlistRoute: typeof ApiAgentWaitlistRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentA2aRoute: ApiAgentA2aRoute,
  ApiAgentCallRoute: ApiAgentCallRoute,
  ApiAgentCardRoute: ApiAgentCardRoute,
  ApiAgentClaudeRoute: ApiAgentClaudeRoute,
  ApiAgentFeeRoute: ApiAgentFeeRoute,
  ApiAgentForumRoute: ApiAgentForumRoute,
  ApiAgentGrokRoute: ApiAgentGrokRoute,
  ApiAgentKeysRoute: ApiAgentKeysRoute,
  ApiAgentMcpRoute: ApiAgentMcpRoute,
  ApiAgentNoticesRoute: ApiAgentNoticesRoute,
  ApiAgentOpenaiRoute: ApiAgentOpenaiRoute,
  ApiAgentOpenapiRoute: ApiAgentOpenapiRoute,
  ApiAgentPingRoute: ApiAgentPingRoute,
  ApiAgentWaitlistRoute: ApiAgentWaitlistRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgentRoute: AgentRoute,
  B3arsRoute: B3arsRoute,
  C0ff33Route: C0ff33Route,
  CoffeeRoute: CoffeeRoute,
  ComputeRoute: ComputeRoute,
  EntityDotjsonRoute: EntityDotjsonRoute,
  F33dRoute: F33dRoute,
  FaqRoute: FaqRoute,
  ForumRoute: ForumRoute,
  GmRoute: GmRoute,
  GuideRoute: GuideRoute,
  HeliosRoute: HeliosRoute,
  HeliosbotRoute: HeliosbotRoute,
  LaunchRoute: LaunchRoute,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRoute,
  OwlRoute: OwlRoute,
  PrivacyRoute: PrivacyRoute,
  R0b0tsRoute: R0b0tsRoute,
  RenewRoute: RenewRoute,
  S1r1usRoute: S1r1usRoute,
  SearchRoute: SearchRoute,
  SecurityRoute: SecurityRoute,
  SitemapRoute: SitemapRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SourceRoute: SourceRoute,
  TermsRoute: TermsRoute,
  ThemeRoute: ThemeRoute,
  VideoSitemapDotxmlRoute: VideoSitemapDotxmlRoute,
  DotwellKnownAgentCardDotjsonRoute: DotwellKnownAgentCardDotjsonRoute,
  DotwellKnownAgentDotjsonRoute: DotwellKnownAgentDotjsonRoute,
  DotwellKnownAiPluginDotjsonRoute: DotwellKnownAiPluginDotjsonRoute,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  MorningPdfIdRoute: MorningPdfIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
