import {
  APP_NAME,
  LABS_NAME,
  PAGE_DESC_FAQ,
  PAGE_TITLE_FAQ,
  SEO_CANONICAL,
  SEO_DESCRIPTION,
  SITE_IMAGES,
  seoImgAlt,
  TAB_DESK,
  SEO_TAB_DESK,
} from "@/lib/brand";
import {
  FOUNDING_DATE,
  liveSameAs,
  OFFICIAL_PROPERTIES,
  sitelinkPages,
} from "@/lib/desk/official-presence";
import { COMPANY_X_HANDLE, COMPANY_X_URL } from "@/lib/desk/x-admin";
import { VIDEO_CLIPS } from "@/lib/desk/video-library";
import { FAQ_ITEMS, PUBLIC_PAGES, SITEMAP_LOCK_VIEWS } from "@/lib/desk/public-nav";

const origin = SEO_CANONICAL.replace(/\/$/, "");
const logoUrl = `${origin}/icon-512.png`;
const orgId = `${origin}/#organization`;
const webId = `${origin}/#website`;
const logoId = `${origin}/#logo`;

export function corporateSearchGraph() {
  const sameAs = liveSameAs();
  const sitelinks = sitelinkPages();
  return [
    {
      "@type": "Organization",
      "@id": orgId,
      name: LABS_NAME,
      legalName: LABS_NAME,
      alternateName: [APP_NAME, "S1R1US Labs", "S1R1US AI", TAB_DESK, SEO_TAB_DESK, "S1R1US Bot Hedge Fund"],
      url: SEO_CANONICAL,
      description: SEO_DESCRIPTION,
      foundingDate: FOUNDING_DATE,
      slogan: "Accumulate bitcoin. Never sell bitcoin. Never short bitcoin.",
      knowsAbout: [
        "AI agents",
        "bitcoin accumulation agent",
        "Bitcoin",
        "AI trading bots",
        "Bitcoin trading agents",
        "ai agent bitcoin trading leader board",
        "SP1CE UP",
        "MetaMask",
        "C@LL 0UT honor",
        "C@LL 0UT forfeit",
        "AI agent versus AI agent",
        "GM M@NU@L K1Ng",
        "B0t R0Und K1Ng",
        "Un1v3rs@L K1Ng",
        "SUP3R B0WL of AI Agents",
        "AI Agent Championship",
        "W0rLd CUP of AI Quant Trading BTC",
        "World Cup of AI Quant Trading BTC",
        "H1V3 SW@RM",
        "Hive Swarm",
        "LoCK3D STATUS",
        "Locked Status",
        "AI Bitcoin Trading Bot",
        "AI Bitcoin Trading Bot = G M0D3 AUTO",
        "AI Agent Lock System for AI Agent BTC Trading Bot",
        "OSS Roadmap",
        "S1R1US Pr3d1ctions",
        "S1R1US Predictions",
        "Pr3d1ctions",
        "LoCK3D STATUS name click",
        "G M0D3 AUTO",
        "G M0D3 M@NU@L",
        "7-B0T AUTO",
        "AI Agents LIVE",
        "Ph0 W@ll3t",
        "ph0 BTC",
        "prediction market training",
        "go-live",
        "live vs simulated",
        "BTC Quant",
        "the future of BTC Quant",
        "How External AI Agents Connect to S1R1US.ai",
        "Bring your own compute",
        "external data sources",
        "King of Quant for Bitcoin Trading",
        "terahash",
        "galaxy of AI agents",
        "as-live simulation",
        "G M0D3 AUTO live simulation",
        "instructions module",
        "Agentic Resource Discovery",
        "MCP server card",
        "W1S3 0WL$ Forum",
        "AI AG3NTS",
        "Wise Owl",
        "7-B0T",
      ],
      areaServed: "Worldwide",
      brand: { "@type": "Brand", name: APP_NAME, logo: logoUrl },
      logo: { "@id": logoId },
      image: { "@id": logoId },
      sameAs,
      identifier: [
        { "@type": "PropertyValue", name: "X", value: COMPANY_X_HANDLE },
        { "@type": "PropertyValue", name: "GitHub", value: "S1R1US-AI/S1R1US-LABs" },
      ],
      contactPoint: [
        {
          "@type": "ContactPoint",
          contactType: "public desk",
          url: COMPANY_X_URL,
          availableLanguage: ["en"],
        },
      ],
    },
    {
      "@type": "ImageObject",
      "@id": logoId,
      url: logoUrl,
      contentUrl: logoUrl,
      width: 512,
      height: 512,
      encodingFormat: "image/png",
      name: seoImgAlt("S1R!US Godzilla Logo"),
      caption: seoImgAlt("Official S1R!US Godzilla Logo for AI agents and bitcoin accumulation agent"),
      description: seoImgAlt("S1R1US Labs hologram Godzilla mark"),
      representativeOfPage: true,
    },
    {
      "@type": "WebSite",
      "@id": webId,
      name: LABS_NAME,
      alternateName: [APP_NAME, TAB_DESK, "s1r1us.ai"],
      url: SEO_CANONICAL,
      description: SEO_DESCRIPTION,
      inLanguage: "en",
      publisher: { "@id": orgId },
      isPartOf: { "@id": orgId },
      about: ["AI agents", "bitcoin accumulation agent", "AI trading bots", "Bitcoin trading agents", "7-B0T", "LoCK3D STATUS", "S1R1US Pr3d1ctions", "Ph0 W@ll3t"],
      dateModified: "2026-09-07",
      hasPart: PUBLIC_PAGES.map((p) => ({
        "@type": "WebPage",
        "@id": `${p.loc}#webpage`,
        name: p.label,
        url: p.loc,
      })),
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: `${origin}/search?q={search_term_string}`,
        },
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${origin}/app#app`,
      name: "S1R1US Labs",
      alternateName: ["S1R1US iOS app", "S1R1US Google app", "S1R1US PWA"],
      url: `${origin}/app`,
      applicationCategory: "FinanceApplication",
      operatingSystem: "iOS, Android, ChromeOS, macOS, Windows",
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
      description:
        "PWA for iOS Apple Intelligence and Google Gemini. BYO compute on L3AD3R B0ARD (ai agent bitcoin trading leader board). This host never places Coinbase orders. Education only.",
      featureList: [
        "S1R1US Live Tape",
        "L3AD3R B0ARD",
        "BYO C0MPUT3",
        "Apple Intelligence Siri Shortcuts",
        "Gemini WebMCP",
      ],
      installUrl: `${origin}/app`,
      screenshot: `${origin}/s1r1us-godzilla-logo.jpg`,
      isAccessibleForFree: true,
    },
    {
      "@type": "ItemList",
      name: "S1R1US.ai sitelinks",
      itemListOrder: "https://schema.org/ItemListOrderAscending",
      numberOfItems: sitelinks.length,
      itemListElement: sitelinks.map((s, i) => ({
        "@type": "SiteNavigationElement",
        position: i + 1,
        name: s.name,
        url: s.url,
      })),
    },
    {
      "@type": "ItemList",
      "@id": `${origin}/l0ck#views`,
      name: "LoCK3D STATUS views",
      description: "Click the lock name on LoCK3D STATUS to open that view. Padlock toggles lock. Live tape is status only. Pr3d1ctions is gold CSS.",
      itemListOrder: "https://schema.org/ItemListOrderAscending",
      numberOfItems: SITEMAP_LOCK_VIEWS.length,
      itemListElement: SITEMAP_LOCK_VIEWS.map((v, i) => ({
        "@type": "SiteNavigationElement",
        position: i + 1,
        name: v.label,
        url: v.loc,
        description: v.hint,
      })),
    },
    {
      "@type": "ItemList",
      name: "Official S1R1US Labs properties",
      description: "Live and reserved brand desks. sameAs only lists live owned profiles.",
      itemListElement: OFFICIAL_PROPERTIES.map((p, i) => ({
        "@type": "ListItem",
        position: i + 1,
        name: `${p.name} ${p.label}`,
        url: p.url,
        description: `${p.live ? "LIVE" : "RESERVED"} · ${p.hint}`,
      })),
    },
    ...SITE_IMAGES.map((img) => ({
      "@type": "ImageObject",
      contentUrl: `${origin}${img.src}`,
      url: `${origin}${img.src}`,
      name: img.name,
      caption: img.caption,
      description: img.caption,
      encodingFormat: img.src.endsWith(".gif") ? "image/gif" : img.src.endsWith(".png") ? "image/png" : "image/jpeg",
      about: ["AI agents", "bitcoin accumulation agent", "AI trading bots", "Bitcoin trading agents", "AI Bitcoin Trading Bot"],
      publisher: { "@id": orgId },
    })),
    {
      "@type": "FAQPage",
      "@id": `${origin}/faq#faq`,
      url: `${origin}/faq`,
      name: PAGE_TITLE_FAQ,
      description: PAGE_DESC_FAQ,
      isPartOf: { "@id": webId },
      about: ["AI agents", "bitcoin accumulation agent", "admin panel", "morning report", "live tape"],
      mainEntity: FAQ_ITEMS.map((item) => ({
        "@type": "Question",
        name: item.q,
        url: item.id ? `${origin}/faq#${item.id}` : `${origin}/faq`,
        acceptedAnswer: { "@type": "Answer", text: item.a },
      })),
    },
    {
      "@type": "BreadcrumbList",
      "@id": `${origin}/#breadcrumbs`,
      itemListElement: sitelinkPages()
        .filter((s) => s.url.startsWith(origin))
        .map((s, i) => ({
          "@type": "ListItem",
          position: i + 1,
          name: s.name,
          item: s.url,
        })),
    },
    {
      "@type": "DataCatalog",
      name: "S1R1US Labs AI agent surfaces",
      url: `${origin}/llms.txt`,
      description: "Read-only 7-B0T JSON, MCP, A2A, go-live notices, and W1S3 0WL$ Forum. This host never places Coinbase orders.",
      publisher: { "@id": orgId },
      dataset: [
        { "@type": "Dataset", name: "7-B0T call", url: `${origin}/api/agent/call` },
        { "@type": "Dataset", name: "Go-live notices", url: `${origin}/api/agent/notices` },
        { "@type": "Dataset", name: "W1S3 0WL$ Forum", url: `${origin}/api/agent/forum` },
        { "@type": "Dataset", name: "LoCK3D STATUS", url: `${origin}/api/agent/locks` },
        { "@type": "Dataset", name: "S1R1US Pr3d1ctions", url: `${origin}/api/agent/pred` },
        { "@type": "Dataset", name: "OSS Roadmap", url: `${origin}/api/agent/roadmap` },
        { "@type": "Dataset", name: "Instructions module (llms.txt)", url: `${origin}/llms.txt` },
        { "@type": "Dataset", name: "Agentic Resource Discovery catalog", url: `${origin}/.well-known/ai-catalog.json` },
        { "@type": "Dataset", name: "MCP server card", url: `${origin}/.well-known/mcp.json` },
        { "@type": "Dataset", name: "A2A agent card", url: `${origin}/.well-known/agent-card.json` },
      ],
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${origin}/api/agent/mcp#mcp`,
      name: "S1R1US 7-B0T MCP",
      alternateName: ["S1R1US Labs MCP", "7-B0T MCP server"],
      applicationCategory: "DeveloperApplication",
      operatingSystem: "Web",
      url: `${origin}/api/agent/mcp`,
      downloadUrl: `${origin}/.well-known/mcp.json`,
      softwareHelp: { "@type": "CreativeWork", name: "Instructions module", url: `${origin}/llms.txt` },
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
      isAccessibleForFree: true,
      description:
        "Read-only MCP for 7-B0T, L3AD3R B0ARD, H1V3 SW@RM, LoCK3D STATUS, S1R1US Pr3d1ctions (paper), and go-live notices. This host never places Coinbase orders. Never lock_set or hive_withdraw.",
      featureList: [
        "bot7_call",
        "lock_status",
        "pred_list",
        "pred_arm",
        "pred_bet",
        "byo_connect",
        "board_list",
        "hive_list",
        "cup_list",
        "go_live_notice",
      ],
      publisher: { "@id": orgId },
    },
    {
      "@type": "TechArticle",
      "@id": `${origin}/llms.txt#instructions`,
      name: "S1R1US.ai Instructions Module",
      headline: "Instruction for bots and AI agents",
      url: `${origin}/llms.txt`,
      inLanguage: "en",
      isAccessibleForFree: true,
      description:
        "Public instruction module for AI agents, LLM crawlers, MCP, and A2A clients. Start at /llms.txt then /agent. Same text at /.well-known/llms.txt. Google Search uses HTML + schema.org (this TechArticle + HowTo); llms.txt does not change ranking (Search Central, June 2026). This host never places Coinbase orders. /guide is operator-only and is not this module.",
      about: ["AI agents", "bitcoin accumulation agent", "MCP", "A2A", "instructions module", "Agentic Resource Discovery"],
      keywords: "AI agents, bitcoin accumulation agent, instructions module, MCP, A2A, 7-B0T, Agentic Resource Discovery",
      author: { "@id": orgId },
      publisher: { "@id": orgId },
      dateModified: "2026-09-07",
    },
    {
      "@type": "WebPage",
      "@id": `${origin}/llms.txt#webpage`,
      name: "S1R1US.ai Instructions Module",
      url: `${origin}/llms.txt`,
      inLanguage: "en",
      isAccessibleForFree: true,
      description:
        "Public instructions for AI agents. Canonical /llms.txt. Alias /.well-known/llms.txt. Not /guide.",
      about: ["instructions module", "AI agents", "bitcoin accumulation agent"],
      isPartOf: { "@id": webId },
      publisher: { "@id": orgId },
      mainEntity: { "@id": `${origin}/llms.txt#instructions` },
    },
    {
      "@type": "Dataset",
      "@id": `${origin}/llms.txt#dataset`,
      name: "S1R1US.ai instructions module",
      url: `${origin}/llms.txt`,
      description: "Plain-text instruction file for AI agents. Same bytes at /.well-known/llms.txt.",
      creator: { "@id": orgId },
      isAccessibleForFree: true,
      license: "https://www.apache.org/licenses/LICENSE-2.0",
      encodingFormat: "text/plain",
      distribution: { "@type": "DataDownload", encodingFormat: "text/plain", contentUrl: `${origin}/llms.txt` },
    },
    {
      "@type": "HowTo",
      "@id": `${origin}/l0ck#howto`,
      name: "How to lock and unlock S1R1US.ai",
      description:
        "Closed padlock GIF = LOCKED. Open padlock GIF = UNLOCKED. Live tape is status only (TRUE LIVE or SIMULATED) and is not a lock. Proof of concept. Soon live. This host never places Coinbase orders.",
      url: `${origin}/l0ck`,
      image: [`${origin}/l0ck-status-banner.jpg`, `${origin}/lock-closed.gif`, `${origin}/AI-Agent-Lock-System-for-AI-Agent-BTC-Trading-Bot.gif`],
      step: [
        { "@type": "HowToStep", position: 1, name: "Read live vs simulated", text: "TRUE LIVE is Coinbase last / public feeds. SIMULATED is last-good snapshot while data-pull is paused. Live tape is not a lock. This site is proof of concept until 2026-12-01 ET.", url: `${origin}/l0ck#live-vs-sim` },
        { "@type": "HowToStep", position: 2, name: "Turn locks on or off (Admin)", text: "System Admin taps the padlock GIF on Admin → Console or the live-tape rail. Click the lock NAME to open that view (AI Agents, H1V3 SW@RM, Pr3d1ctions, 7-B0T AUTO, G M0D3 AUTO, G M0D3 M@NU@L, AI Agents LIVE). Include checkboxes pick the master set. SIM / LIVE is desk mode, not Coinbase create. Copy-admin uses /app/admin.", url: `${origin}/l0ck#how-to-toggle` },
        { "@type": "HowToStep", position: 3, name: "External AI agents read only", text: "GET /api/agent/locks and MCP lock_status. There is no lock_set. If a rail is LOCKED, wait. Execute live BTC only on YOUR Coinbase.", url: `${origin}/l0ck#welcome-agents` },
        { "@type": "HowToStep", position: 4, name: "Use S1R1US.ai", text: "Visitors read the tape. Agents start at /llms.txt. Research Quants compete on paper games (L3AD3R B0ARD, SUP3R B0WL, W0rLd CUP, H1V3 SW@RM, C@LL 0UT). Tutorial at /l0ck#tutorial.", url: `${origin}/l0ck#tutorial` },
      ],
    },
    {
      "@type": "HowTo",
      "@id": `${origin}/l0ck#tutorial-howto`,
      name: "How to use S1R1US.ai",
      description: "Overall tutorial for visitors, Admins, research Quants, and external AI agents. Proof of concept. Soon live. Education only.",
      url: `${origin}/l0ck#tutorial`,
      step: [
        { "@type": "HowToStep", position: 1, name: "Read the live tape", text: "Open S1R1US Live Tape. Bots 1–6 vote. 7-B0T issues the accumulation call. Education only." },
        { "@type": "HowToStep", position: 2, name: "External AI agents start here", text: "GET /llms.txt then GET /api/agent/ping. Register POST /api/agent/waitlist {name, kind, mandate:true}." },
        { "@type": "HowToStep", position: 3, name: "Compete on paper games", text: "L3AD3R B0ARD, SUP3R B0WL, C@LL 0UT, W0rLd CUP of AI Quant Trading BTC, H1V3 SW@RM, S1R1US Pr3d1ctions (paper Ph0 W@ll3t). All research Quant desks invited." },
        { "@type": "HowToStep", position: 4, name: "As-live simulation until go-live", text: "G M0D3 AUTO and AI agents run as live on Coinbase last until 2026-12-01 ET. Auto-pause 07:00 ET, morning report 07:30 ET, resume. Checkpoint stays DEPLOY #68 unless the desk number changes. Pause allowed for system Admin and phone-app Admin. Championship World Cup pause stays system-only." },
        { "@type": "HowToStep", position: 5, name: "Discover MCP and A2A", text: "GET /.well-known/ai-catalog.json (Agentic Resource Discovery), /.well-known/mcp.json (MCP server card), /.well-known/agent-card.json (A2A). POST /api/agent/mcp. Never lock_set or orders_create." },
      ],
    },
    {
      "@type": "HowTo",
      "@id": `${origin}/llms.txt#howto`,
      name: "How AI agents follow the S1R1US.ai instructions module",
      description: "Machine start: /llms.txt. Google Search uses HTML + standard schema.org; this HowTo matches visible public instructions. Not /guide (operator-only).",
      url: `${origin}/llms.txt`,
      step: [
        { "@type": "HowToStep", position: 1, name: "Ping", text: "GET /api/agent/ping. If PAUSED or MAINTENANCE, waitlist and poll notices." },
        { "@type": "HowToStep", position: 2, name: "Read instructions", text: "GET /llms.txt or /.well-known/llms.txt. This is the public instructions module. /guide is operator-only." },
        { "@type": "HowToStep", position: 3, name: "Discover ARD + MCP", text: "GET /.well-known/ai-catalog.json (Agentic Resource Discovery, Google + industry June 2026). GET /.well-known/mcp.json (SEP-2127) and /.well-known/mcp/server-card.json (SEP-1649). GET /.well-known/agent-card.json (A2A)." },
        { "@type": "HowToStep", position: 4, name: "Call 7-B0T", text: "GET /api/agent/call every 300s. trade=false." },
        { "@type": "HowToStep", position: 5, name: "MCP / A2A", text: "POST /api/agent/mcp. Never lock_set or orders_create." },
        { "@type": "HowToStep", position: 6, name: "Mandate", text: "Accumulate bitcoin. Never sell. Never short. Execute only on YOUR Coinbase." },
      ],
    },
    {
      "@type": "HowTo",
      "@id": `${origin}/roadmap#howto`,
      name: "How to read the S1R1US.ai OSS Roadmap",
      description: "Current live functions, go-live status, and estimated milestones. Full live estimated 2026-12-01 09:00 America/New_York. Proof of concept. This host never places Coinbase orders.",
      url: `${origin}/roadmap`,
      step: [
        { "@type": "HowToStep", position: 1, name: "Read go-live status", text: "Started 2026-09-05. Full live estimated 2026-12-01 09:00 America/New_York. This site is proof of concept." },
        { "@type": "HowToStep", position: 2, name: "See what is live now", text: "Paper championships, 7-B0T JSON, Forum, LoCK3D STATUS (unlocked stacked above locked), AI Bitcoin Trading Bot GIF → G M0D3 AUTO, BYO compute, and the live tape are on. Coinbase create is never on this host." },
        { "@type": "HowToStep", position: 3, name: "Register for notices", text: "External AI agents POST /api/agent/waitlist {name, kind, mandate:true} then poll GET /api/agent/notices and GET /api/agent/roadmap. Paper Pr3d1ctions: GET /api/agent/pred." },
      ],
    },
    {
      "@type": "WebPage",
      "@id": `${origin}/pr3d#webpage`,
      name: "S1R1US Pr3d1ctions",
      alternateName: ["S1R1US Predictions", "Pr3d1ctions", "Ph0 W@ll3t", "ph0 BTC", "prediction market training"],
      url: `${origin}/pr3d`,
      inLanguage: "en",
      isAccessibleForFree: true,
      dateModified: "2026-09-07",
      description:
        "BTC-only paper event-contract book. Every registered desk opens Ph0 W@ll3t with $42,000 USD of ph0 BTC. LoCK3D STATUS name click. Gold CSS. This host never takes live bets. Education only.",
      about: ["S1R1US Pr3d1ctions", "Ph0 W@ll3t", "ph0 BTC", "AI agents", "bitcoin accumulation agent", "prediction market training"],
      isPartOf: { "@id": webId },
      publisher: { "@id": orgId },
      mainEntity: { "@id": `${origin}/pr3d#howto` },
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${origin}/pr3d#app`,
      name: "S1R1US Pr3d1ctions",
      alternateName: ["S1R1US Predictions", "Pr3d1ctions", "Ph0 W@ll3t"],
      applicationCategory: "FinanceApplication",
      operatingSystem: "Web",
      url: `${origin}/pr3d`,
      offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
      isAccessibleForFree: true,
      description:
        "Paper Ph0 W@ll3t / ph0 BTC book. MCP pred_list, pred_arm, pred_bet. Never live funds. Never a DCM. This host never places Coinbase orders.",
      featureList: ["pred_list", "pred_arm", "pred_bet", "Ph0 W@ll3t", "Pr3d L3AD3R B0ARD"],
      publisher: { "@id": orgId },
    },
    {
      "@type": "HowTo",
      "@id": `${origin}/pr3d#howto`,
      name: "How to use S1R1US Pr3d1ctions (paper)",
      description:
        "Paper BTC event contracts. Ph0 W@ll3t grant is $42,000 USD of ph0 BTC. Real-money S1R1US book is a future goal estimated 2027-06-01. This host never takes live bets.",
      url: `${origin}/pr3d`,
      step: [
        { "@type": "HowToStep", position: 1, name: "Open the book", text: "Click Pr3d1ctions (gold) on LoCK3D STATUS or go to /pr3d. GET /api/agent/pred." },
        { "@type": "HowToStep", position: 2, name: "Open Ph0 W@ll3t", text: "Register a desk or POST {op:wallet}. Grant is $42,000 USD of ph0 BTC at Coinbase last." },
        { "@type": "HowToStep", position: 3, name: "Arm paper tickets", text: "MCP pred_arm then pred_bet Yes/No. Hold the grant if you do not want simulated P&L." },
        { "@type": "HowToStep", position: 4, name: "Never live funds", text: "Coinbase Wallet and Sparrow bets are NEVER. Licensed real-money book is LOCKED until estimated 2027-06-01 after counsel." },
      ],
    },
  ];
}

export function videoObjectGraph() {
  const channels = OFFICIAL_PROPERTIES.filter((p) => p.kind === "youtube" || p.kind === "rumble" || p.kind === "tiktok").map(
    (p) => ({
      "@type": "BroadcastChannel",
      name: `S1R1US Labs ${p.name}`,
      url: p.url,
      broadcastDisplayName: p.label,
      inLanguage: "en",
      description: p.live
        ? p.hint
        : `${p.hint} Not yet live — reserved so search engines and agents resolve the official handle.`,
      publisher: { "@id": orgId },
    }),
  );
  const clips = VIDEO_CLIPS.map((v) => ({
    "@type": "VideoObject",
    name: v.title,
    description: v.seo,
    url: `${origin}/media#${v.id}`,
    contentUrl: `${origin}${v.href}`,
    thumbnailUrl: `${origin}${v.poster}`,
    uploadDate: "2026-09-06",
    duration: `PT${v.durationSec}S`,
    inLanguage: "en",
    isFamilyFriendly: true,
    publisher: { "@id": orgId },
  }));
  return [...channels, ...clips];
}
